### PR TITLE
`arb_vec` module

### PR DESCRIPTION
**Pull request by albinahlback**
Update documentation and build system accordingly

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Not sure if having this as a separate module adds much value. How about just deinlining all the vector functions in ``arb.h``?

**Comment by albinahlback** [comment]
I think it has the same characteristic as most other vector modules. What makes the arb/acb vector "module" special?

**Comment by fredrik-johansson** [comment]
I rather think that the other ``X_vec`` modules are a bit superfluous and in most cases could be combined with ``X``.

**Comment by albinahlback** [comment]
Alright!

**Pull request closed without merging**
