### PR TITLE
Add modular splitting

### PR DESCRIPTION
**Pull request by David-Berghaus**
Added modular splitting as described in [Brent, Zimmermann: Modern Computer Arithmetic, Section 4.4.3](https://maths-people.anu.edu.au/~brent/pd/mca-cup-0.5.9.pdf).

Remarks:
-I ended up not using `set_shallow` because the `swap`-approach has the convenience that all coefficients that are out of bounds are simply zero entries which are ignored by the dot product routines.
-I started working on `gr_poly_evaluate_other_modular` but stopped since I noticed that `gr_dot_other` still uses the naive method. We therefore cannot get a performance advantage over `gr_poly_evaluate_other_rectangular` but potentially worse numerical stability.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
This will be a nice algorithm to have!

The code needs a little bit of work. You can't safely swap entries from ``poly`` because this is a read-only argument: it may be read simultaneously from another thread, for example. So ``tmp`` should actually be allocated shallowly and ``set_shallow`` should be used. See gr_mat/nonsingular_solve_tril.c for an example. For the dot product where you're currently zero-padding, you should be able to calculate the actual length.

Indeed, this algorithm could be implemented more cleanly if ``gr_dot`` supported strided access which is unfortunately not the case.

> -I started working on gr_poly_evaluate_other_modular but stopped since I noticed that gr_dot_other still uses the naive method. We therefore cannot get a performance advantage over gr_poly_evaluate_other_rectangular but potentially worse numerical stability.

Yes, this will make sense to add when we have an overloadable ``gr_dot_other`` / ``gr_other_dot``.

**Comment by David-Berghaus** [comment]
Oh yes, I was stupid and didn't think of potential multi-threading!

I replaced `swap` with `set_shallow` now.

**Comment by fredrik-johansson** [comment]
Just some minor style issues to fix: use ``/* */`` comments, ``{`` on new lines.

**Comment by fredrik-johansson** [comment]
BTW, ``gr_fmpz_poly_evaluate_modular`` is documented but does not seem to be part of the PR.

**Comment by fredrik-johansson** [comment]
Nice!

**Comment by fredrik-johansson** [comment]
I pushed a small optimization: the variable ``tmp_gr`` is not needed if you compute one more entry in the x vector.

**Pull request merged**
