### PR TITLE
Recognize Comet Lake U in config.guess

### LINKED ISSUE #2073: CPU detection issue
Flint's `configure` on my laptop says
```
checking if system have required x86_64 instruction set for fft_small... no
checking if system can use FLINT's fft_small module... no
configure: WARNING: Currently no assembly available for nehalem-pc-linux-gnu. Disabling assembly...
```
presumably because
```
~/co/flint:main$ config/config.guess
nehalem-pc-linux-gnu
```
but the cpu is an i7-10810U (“Comet Lake”, avx2, no avx512) which I thought should be enough for much of the assembly code in Flint.

### PR DESCRIPTION
**Pull request by albinahlback**
@mezzarobba could you check that this resolves #2073?

### CODE REVIEW

**Comment by mezzarobba** [comment]
On Monday, 23 September 2024 20:04:07 CEST Albin Ahlbäck wrote:
> @mezzarobba could you check that this resolves #2073?

Almost: it should be 0xa6, not 0x8e. Thanks for looking into it!

-- 
Marc

**Comment by albinahlback** [comment]
Corrected to `0xa6`. I have previously taken everything from https://en.wikichip.org/wiki/intel/cpuid as Intel do not seem to document these things for the public (at least I have a hard time finding this stuff). Anyway, give it a try!

**Comment by mezzarobba** [comment]
On Monday, 23 September 2024 21:33:52 CEST Albin Ahlbäck wrote:
> Corrected to `0xa6`. I have previously taken everything from
> https://en.wikichip.org/wiki/intel/cpuid as Intel do not seem to
> document these things for the public (at least I have a hard time
> finding this stuff). Anyway, give it a try!

Yes, it works now, thanks! I do get a warning that
```
/usr/bin/ld: warning: build/mpn_extras/x86_64/broadwell/
sqrhigh_normalised_hard.lo: missing .note.GNU-stack section implies 
executable stack
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a 
future version of the linker
Building libflint.so.20.0.0
/usr/bin/ld: warning: build/mpn_extras_merged.lo: requires executable 
stack (because the .note.GNU-stack section is executable)
```
but I guess that's a different issue.

**Comment by albinahlback** [comment]
Yeah, seems like an opt-in in ld ([source](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ffcf9c5700e49c0aee42dcba9a12ba21338e8136)). I'll open up another issue about this.

Thanks!

**Pull request merged**
