### PR TITLE
Basic printing functions for nmod_vec

### PR DESCRIPTION
**Pull request by vneiger**
This adds some basic IO functions for `nmod_vec`, mimicking those for `nmod_mat`.

### CODE REVIEW

**Comment by vneiger** [comment]
> This is very useful. Could you add them to the documentation also?

Yes, done. And also completed the related one of `nmod_mat` .

**Comment by edgarcosta** [comment]
Not to derail this effort, but would writing this kind of tool in the generic rings make more sense?
(and I would love someone to give me an option for the separator, e.g., `, `, as it makes it easier to copy it into a CAS)

**Comment by vneiger** [comment]
> Not to derail this effort, but would writing this kind of tool in the generic rings make more sense? (and I would love someone to give me an option for the separator, e.g., `, `, as it makes it easier to copy it into a CAS)

Yes ultimately it would be nice to have such printing in generics (in fact @fredrik-johansson  just showed me there is some generics printing already), and also yes for a custom separator. Right now I just wanted to add this piece of code that I had already done some time ago. Should we make an issue to make sure this perspective (generics + separator) does not get forgotten?

**Comment by vneiger** [comment]
> Awesome possum! please someone make an issue I'm on mobile

Issue created. #1502

**Pull request merged**
