### PR TITLE
Update links from http to https

### PR DESCRIPTION
**Pull request by fingolfin**
The first two commits are generated by a script. The final one contains manual adjustments (and one fix where `http://http://www` was used)

### CODE REVIEW

**Comment by fingolfin** [comment]
fine by me. I could e.g. update the PR next week. That said, there are many active PRs, so I wouldn't be surprised if this had to be repeated 1-2 times anyway *shrug*.

**Comment by albinahlback** [comment]
I don't think there should be any conflicts. Looks good to go in my opinion!

**Comment by fingolfin** [comment]
I've rebased this now once again. Hopefully it can be merged now?

**Comment by fredrik-johansson** [comment]
Sure. Thanks for the update!

**Pull request merged**
