### PR TITLE
New longlong.h

### PR DESCRIPTION
**Pull request by albinahlback**
Added support for Windows and Clang.

### CODE REVIEW

**Comment by albinahlback** [comment]
Basically, the idea is to clean up `longlong.h`, add support for MSVC and change the macros for Clang.

**Comment by albinahlback** [comment]
I also want to say that the assembly instructions for ARM64 is never used in the current longlong.h as GCC never defines __arm64__, but rather __aarch64__. I think I stated this in the old PR.

**Comment by fredrik-johansson** [comment]
> I also want to say that the assembly instructions for ARM64 is never used in the current longlong.h as GCC never defines arm64, but rather aarch64.

Yeah, that's a big issue! See my timings on M1 in #1674.

**Comment by fredrik-johansson** [comment]
Yeah, I can confirm that this fixes the performance for both aarch64 and clang(x86_64) encountered in #1674.

Strong merge!

**Pull request merged**
