### PR TITLE
distribute configure, aclocal.m4

### PR DESCRIPTION
**Pull request by mezzarobba**

### CODE REVIEW

**Comment by edgarcosta** [comment]
fyi, `git archive` supports `--format=tar.gz`, thus one can simplify the first line of `dist`

**Comment by mezzarobba** [comment]
That's also what I thought, but I didn't bother to check...

**Comment by mezzarobba** [comment]
Actually we could even do something like
```diff
diff --git a/Makefile.in b/Makefile.in
index 146c6dcce..d107957f5 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -790,11 +790,12 @@ endif
 configure aclocal.m4 src/config.h.in &: bootstrap.sh configure.ac acinclude.m4
        ./$<

-DIST_PREFIX := flint-$(FLINT_MAJOR).$(FLINT_MINOR).$(FLINT_PATCH)/
+DIST_NAME := flint-$(FLINT_MAJOR).$(FLINT_MINOR).$(FLINT_PATCH)

-dist: configure aclocal.m4 src/config.h.in
-       git archive --format tar.gz --prefix ${DIST_PREFIX}src/ $(patsubst %,--add-file %,$(filter src/%,$^)) --prefix ${DIST_PREFIX}  $(patsubst %,--add-file %,$(filter-out src/%,$^)) origin/flint-$(FLINT_MAJOR).$(FLINT_MINOR) > ../flint-$(FLINT_MAJOR).$(FLINT_MINOR).$(FLINT_PATCH).tar.gz
-       git archive --format zip --prefix ${DIST_PREFIX}src/ $(patsubst %,--add-file %,$(filter src/%,$^)) --prefix ${DIST_PREFIX}  $(patsubst %,--add-file %,$(filter-out src/%,$^)) origin/flint-$(FLINT_MAJOR).$(FLINT_MINOR) > ../flint-$(FLINT_MAJOR).$(FLINT_MINOR).$(FLINT_PATCH).zip
+../$(DIST_NAME).%: FORCE
+       git archive --format $* --prefix ${DIST_NAME}/src/ --add-file src/config.h.in --prefix ${DIST_NAME}/ --add-file configure --add-file aclocal.m4 origin/flint-$(FLINT_MAJOR).$(FLINT_MINOR) > $@
+
+dist: ../$(DIST_NAME).tar.gz ../$(DIST_NAME).zip

 ################################################################################
 # debugging
@@ -803,4 +804,6 @@ dist: configure aclocal.m4 src/config.h.in
 print-%:
        @echo "$*=$($*)"

+FORCE:
+
 .PHONY: all library shared static examples profile tests check tune valgrind clean distclean install uninstall dist %_TEST_RUN %_VALGRIND_RUN print-% coverage
```
Not sure if this is better of worse. Any opinions?

**Comment by edgarcosta** [comment]
It is better, as I only need to parse one line instead of two identical lines.

What is the point of `FORCE`?

**Comment by mezzarobba** [comment]
Since the output is based on the contents of the git repo itself and not just on the worktree, I think we want `make dist` to recreate the archives even if they appear to be up-to-date. Since the rule contains a wildcard, we cannot just declare it as `.PHONY`.

**Comment by mezzarobba** [comment]
(Marking the PR as draft again because I forgot some files.)

**Comment by mezzarobba** [comment]
ok, here is a version that works for me...

**Comment by edgarcosta** [comment]
Thanks for the explanation

**Comment by AndreasEnge** [comment]
I tried it out, and the code creates a .tar.gz that I can unpack and that allows me to do "./configure" and "make".

As someone used to autotools, the different behaviour is a bit surprising; I am used to trying "make dist" (actually, "make distcheck") just in my source code checkout, whereas here a branch "origin/flint-x.y" is expected. For the maintainer, I suppose this patch does the desired thing.

**Comment by fingolfin** [comment]
This seems to duplicate the work I already did on #1449 ?

**Comment by mezzarobba** [comment]
Indeed! Sorry for the noise.

**Pull request closed without merging**
