### PR TITLE
Add -O3 and -march=native to default CFLAGS

### PR DESCRIPTION
**Pull request by albinahlback**
But don't use -march=native if build != host

Solves #1357

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
fft_small assumes that ulong is 64-bit all over the place and will need disabling on 32-bit.

**Comment by albinahlback** [comment]
Would be nice to get fft_small working for CMake. I'll try and see if it works, but this seems good as for now.

**Comment by albinahlback** [comment]
Yeah, I should add an option for disabling this. Thanks for bringing this up!

**Comment by oscarbenjamin** [comment]
Was an option added to disable this?

We need to disable it in python-flint for the wheels uploaded to PyPI (https://github.com/flintlib/python-flint/issues/165).

My first thought was that passing `--host=x86_64-pc-linux-gnu` would disable this. At least that seems to be how it works with GMP. Setting `--host` doesn't seem to make any difference though.

**Comment by albinahlback** [comment]
> Was an option added to disable this?

No, the idea is to use pass the host to `--host`.

> My first thought was that passing `--host=x86_64-pc-linux-gnu` would disable this. At least that seems to be how it works with GMP. Setting `--host` doesn't seem to make any difference though.

It works for me. Can you post the output of `configure` as well as `CFLAGS` from Makefile?

**Comment by edgarcosta** [comment]
On my laptop:
```
(make distclean; ./bootstrap.sh && ./configure --host=x86_64-pc-linux-gnu && make print-CFLAGS) | gist                                                                                         1 ✘  6s
make: *** No rule to make target `distclean'.  Stop.
autoreconf: export WARNINGS=all
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: aclocal
autoreconf: running: /usr/local/Cellar/autoconf/2.72/bin/autoconf
autoreconf: running: /usr/local/Cellar/autoconf/2.72/bin/autoheader
autoreconf: configure.ac: not using Automake
autoreconf: Leaving directory '.'
configure: WARNING: Currently no assembly available for x86_64-pc-linux-gnu. Disabling assembly...
```
`CFLAGS=-Wall -Werror=implicit-function-declaration -std=c11 -pedantic -O3 -g ` and the rest of the log is at:
https://gist.github.com/edgarcosta/e07d05004378cf355dbe4d60ef292d29

**Comment by edgarcosta** [comment]
Here is an example:
with flint-3.1.3-p1
```
./configure --prefix=/project/.local --host=x86_64-pc-linux-gnu --disable-assembly --disable-avx2 --disable-avx512 --with-gmp=/project/.local --with-mpfr=/project/.local --disable-static --disable-debug
```
gives
```
CFLAGS=-pedantic -std=c11 -march=native -O3 -Werror=implicit-function-declaration -Wno-stringop-overflow -Wno-stringop-overread -Wall 
```
https://github.com/edgarcosta/python-flint/actions/runs/10048388011/job/27772260101#step:7:4351

**Comment by albinahlback** [comment]
Ah, yes. So the flag `--enable-arch` was added (hence, you could push `--disable-arch`). However, this is deprecated now, and everything should be pushed into `--host`.

**Comment by edgarcosta** [comment]
Here is an example with the nightly release:
```
 ./configure --prefix=/project/.local --host=x86_64-pc-linux-gnu --disable-assembly --disable-avx2 --disable-avx512 --with-gmp=/project/.local --with-mpfr=/project/.local --disable-static --disable-debug
 ```
 gives
```
CFLAGS=-Wno-stringop-overflow -Wno-stringop-overread -Wall -Werror=implicit-function-declaration -std=c11 -pedantic -O3
```

https://github.com/edgarcosta/python-flint/actions/runs/10048548865/job/27772751502#step:7:4498

**Comment by edgarcosta** [comment]
ps: @oscarbenjamin , I do not understand the `ImportError: /tmp/tmp.mgMI5IM6jP/venv/lib/python3.9/site-packages/flint/pyflint.cpython-39-x86_64-linux-gnu.so: undefined symbol: flint_rand_init` in the example above, given https://github.com/flintlib/python-flint/blob/master/src/flint/flintlib/flint.pxd#L46

**Comment by oscarbenjamin** [comment]
> > My first thought was that passing `--host=x86_64-pc-linux-gnu` would disable this. At least that seems to be how it works with GMP. Setting `--host` doesn't seem to make any difference though.
> 
> It works for me. Can you post the output of `configure` as well as `CFLAGS` from Makefile?

With this PR: https://github.com/flintlib/python-flint/pull/166. The PR sets `--host=x86_64-pc-linux-gnu` passing the same value as used for building GMP:
https://github.com/flintlib/python-flint/blob/2e4b0ab69b711a4d56e8cd8805b7220876ba611e/bin/cibw_before_all_linux.sh#L6
It also sets `--disable-assembly`, `--disable-avx2` and `--disable-avx512`.

The build logs are at https://github.com/flintlib/python-flint/actions/runs/10027185028/job/27712505397?pr=166

Edgar said that the resulting build still did not work on his computer although it passed all tests in CI. I don't have an x86_64 machine available to test on right now.

The configure output is:

<details>
  <summary>Click to expand</summary>

```
2024-07-21T09:16:27.9803010Z checking build system type... x86_64-pc-linux-gnu
2024-07-21T09:16:27.9861705Z checking host system type... x86_64-pc-linux-gnu
2024-07-21T09:16:27.9882382Z checking how to print strings... printf
2024-07-21T09:16:27.9887294Z checking for x86_64-pc-linux-gnu-gcc... no
2024-07-21T09:16:27.9891135Z checking for gcc... gcc
2024-07-21T09:16:28.0466167Z checking whether the C compiler works... yes
2024-07-21T09:16:28.0467022Z checking for C compiler default output file name... a.out
2024-07-21T09:16:28.0769048Z checking for suffix of executables... 
2024-07-21T09:16:28.1130378Z checking whether we are cross compiling... no
2024-07-21T09:16:28.1327324Z checking for suffix of object files... o
2024-07-21T09:16:28.1502288Z checking whether the compiler supports GNU C... yes
2024-07-21T09:16:28.1677701Z checking whether gcc accepts -g... yes
2024-07-21T09:16:28.2090382Z checking for gcc option to enable C11 features... none needed
2024-07-21T09:16:28.2133822Z checking for a sed that does not truncate output... /usr/bin/sed
2024-07-21T09:16:28.2163655Z checking for grep that handles long lines and -e... /usr/bin/grep
2024-07-21T09:16:28.2179319Z checking for egrep... /usr/bin/grep -E
2024-07-21T09:16:28.2196224Z checking for fgrep... /usr/bin/grep -F
2024-07-21T09:16:28.2248504Z checking for ld used by gcc... /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld
2024-07-21T09:16:28.2271298Z checking if the linker (/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld) is GNU ld... yes
2024-07-21T09:16:28.2297110Z checking for BSD- or MS-compatible name lister (nm)... /opt/rh/devtoolset-10/root/usr/bin/nm -B
2024-07-21T09:16:28.2494738Z checking the name lister (/opt/rh/devtoolset-10/root/usr/bin/nm -B) interface... BSD nm
2024-07-21T09:16:28.2495553Z checking whether ln -s works... yes
2024-07-21T09:16:28.2535149Z checking the maximum length of command line arguments... 3145728
2024-07-21T09:16:28.2563635Z checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
2024-07-21T09:16:28.2565921Z checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
2024-07-21T09:16:28.2567881Z checking for /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld option to reload object files... -r
2024-07-21T09:16:28.2572634Z checking for x86_64-pc-linux-gnu-file... no
2024-07-21T09:16:28.2579039Z checking for file... file
2024-07-21T09:16:28.2584180Z checking for x86_64-pc-linux-gnu-objdump... no
2024-07-21T09:16:28.2587947Z checking for objdump... objdump
2024-07-21T09:16:28.2593576Z checking how to recognize dependent libraries... pass_all
2024-07-21T09:16:28.2599554Z checking for x86_64-pc-linux-gnu-dlltool... no
2024-07-21T09:16:28.2604829Z checking for dlltool... no
2024-07-21T09:16:28.2607048Z checking how to associate runtime and link libraries... printf %s\n
2024-07-21T09:16:28.2611558Z checking for x86_64-pc-linux-gnu-ar... no
2024-07-21T09:16:28.2615635Z checking for ar... ar
2024-07-21T09:16:28.2874483Z checking for archiver @FILE support... @
2024-07-21T09:16:28.2877974Z checking for x86_64-pc-linux-gnu-strip... no
2024-07-21T09:16:28.2882065Z checking for strip... strip
2024-07-21T09:16:28.2887047Z checking for x86_64-pc-linux-gnu-ranlib... no
2024-07-21T09:16:28.2890767Z checking for ranlib... ranlib
2024-07-21T09:16:28.2896531Z checking for gawk... gawk
2024-07-21T09:16:28.3507237Z checking command to parse /opt/rh/devtoolset-10/root/usr/bin/nm -B output from gcc object... ok
2024-07-21T09:16:28.3522050Z checking for sysroot... no
2024-07-21T09:16:28.3564015Z checking for a working dd... /usr/bin/dd
2024-07-21T09:16:28.3602552Z checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
2024-07-21T09:16:28.3745905Z checking for x86_64-pc-linux-gnu-mt... no
2024-07-21T09:16:28.3750882Z checking for mt... no
2024-07-21T09:16:28.3784404Z checking if : is a manifest tool... no
2024-07-21T09:16:28.3983191Z checking for stdio.h... yes
2024-07-21T09:16:28.4215838Z checking for stdlib.h... yes
2024-07-21T09:16:28.4475599Z checking for string.h... yes
2024-07-21T09:16:28.4741464Z checking for inttypes.h... yes
2024-07-21T09:16:28.5008194Z checking for stdint.h... yes
2024-07-21T09:16:28.5275574Z checking for strings.h... yes
2024-07-21T09:16:28.5543959Z checking for sys/stat.h... yes
2024-07-21T09:16:28.5818211Z checking for sys/types.h... yes
2024-07-21T09:16:28.6123893Z checking for unistd.h... yes
2024-07-21T09:16:28.6417239Z checking for dlfcn.h... yes
2024-07-21T09:16:28.6454553Z checking for objdir... .libs
2024-07-21T09:16:28.7179731Z checking if gcc supports -fno-rtti -fno-exceptions... no
2024-07-21T09:16:28.7180805Z checking for gcc option to produce PIC... -fPIC -DPIC
2024-07-21T09:16:28.7364916Z checking if gcc PIC flag -fPIC -DPIC works... yes
2024-07-21T09:16:28.7563427Z checking if gcc static flag -static works... no
2024-07-21T09:16:28.7826328Z checking if gcc supports -c -o file.o... yes
2024-07-21T09:16:28.7827193Z checking if gcc supports -c -o file.o... (cached) yes
2024-07-21T09:16:28.7917577Z checking whether the gcc linker (/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld -m elf_x86_64) supports shared libraries... yes
2024-07-21T09:16:28.8204755Z checking whether -lc should be explicitly linked in... no
2024-07-21T09:16:28.8696638Z checking dynamic linker characteristics... GNU/Linux ld.so
2024-07-21T09:16:28.8697503Z checking how to hardcode library paths into programs... immediate
2024-07-21T09:16:28.8715525Z checking whether stripping libraries is possible... yes
2024-07-21T09:16:28.8716487Z checking if libtool supports shared libraries... yes
2024-07-21T09:16:28.8717433Z checking whether to build shared libraries... yes
2024-07-21T09:16:28.8718165Z checking whether to build static libraries... no
2024-07-21T09:16:28.8824901Z checking for a race-free mkdir -p... /usr/bin/mkdir -p
2024-07-21T09:16:28.8974459Z checking for inline... inline
2024-07-21T09:16:28.9655363Z checking whether byte ordering is bigendian... no
2024-07-21T09:16:28.9672749Z checking if memory is strongly-ordered... yes
2024-07-21T09:16:28.9911888Z checking how to run the C preprocessor... gcc -E
2024-07-21T09:16:29.0455454Z checking for gmp.h... yes
2024-07-21T09:16:29.0572348Z checking if version of GMP is greater than 6.2.1... yes
2024-07-21T09:16:29.0751852Z checking if GMP defines mp_limb_t as unsigned long long int... no
2024-07-21T09:16:29.1064590Z checking for mpfr.h... yes
2024-07-21T09:16:29.1186627Z checking if version of MPFR is greater than 4.1.0... yes
2024-07-21T09:16:29.1320021Z checking for desired ABI... 64
2024-07-21T09:16:29.1608569Z checking for stdarg.h... yes
2024-07-21T09:16:29.1980918Z checking for math.h... yes
2024-07-21T09:16:29.2300810Z checking for float.h... yes
2024-07-21T09:16:29.2618679Z checking for errno.h... yes
2024-07-21T09:16:29.2918380Z checking for fenv.h... yes
2024-07-21T09:16:29.3184655Z checking for alloca.h... yes
2024-07-21T09:16:29.3459353Z checking for malloc.h... yes
2024-07-21T09:16:29.3765865Z checking for sys/param.h... yes
2024-07-21T09:16:29.4040350Z checking for windows.h... no
2024-07-21T09:16:29.4314831Z checking for pthread_np.h... no
2024-07-21T09:16:29.4599969Z checking for pthread.h... yes
2024-07-21T09:16:29.5358147Z checking for library containing atan2... -lm
2024-07-21T09:16:29.6098341Z checking for library containing __gmpz_init... -lgmp
2024-07-21T09:16:29.6466796Z checking for library containing __gmpn_gcd_11... none required
2024-07-21T09:16:29.6829400Z checking for library containing __gmpn_div_q... none required
2024-07-21T09:16:29.7197796Z checking for library containing __gmpn_mul_basecase... none required
2024-07-21T09:16:29.8001004Z checking for library containing __gmpn_modexact_1_odd... no
2024-07-21T09:16:29.8367618Z checking for library containing __gmpn_addmul_2... none required
2024-07-21T09:16:29.9130713Z checking for library containing mpfr_init... -lmpfr
2024-07-21T09:16:29.9515538Z checking for library containing mpfr_round_p... none required
2024-07-21T09:16:29.9895510Z checking for library containing mpfr_mulhigh_n... none required
2024-07-21T09:16:30.0270916Z checking for library containing mpfr_sqrhigh_n... none required
2024-07-21T09:16:30.0450742Z checking whether gcc accepts -pthread... yes
2024-07-21T09:16:30.0878104Z checking if cpu_set_t is supported... yes
2024-07-21T09:16:30.1259431Z checking if alloca works... yes
2024-07-21T09:16:30.1704772Z checking for aligned_alloc... yes
2024-07-21T09:16:30.2154582Z checking for _aligned_malloc... no
2024-07-21T09:16:30.2342636Z checking whether gcc accepts -Werror=unknown-warning-option... no
2024-07-21T09:16:30.2531723Z checking whether gcc accepts -Wall... yes
2024-07-21T09:16:30.2708242Z checking whether gcc accepts -Wno-stringop-overread... yes
2024-07-21T09:16:30.2886260Z checking whether gcc accepts -Wno-stringop-overflow... yes
2024-07-21T09:16:30.3061404Z checking whether gcc accepts -Werror=implicit-function-declaration... yes
2024-07-21T09:16:30.3245785Z checking whether gcc accepts -O3... yes
2024-07-21T09:16:30.3450366Z checking whether gcc accepts -march=native... yes
2024-07-21T09:16:30.3624681Z checking whether gcc accepts -std=c11... yes
2024-07-21T09:16:30.3803284Z checking whether gcc accepts -pedantic... yes
2024-07-21T09:16:30.4106253Z checking for host architecture... znver2
2024-07-21T09:16:30.5860465Z checking for immintrin.h... yes
2024-07-21T09:16:30.5959109Z checking if system have required x86_64 instruction set for fft_small... yes
2024-07-21T09:16:30.5961143Z checking if system can use FLINT's fft_small module... yes
2024-07-21T09:16:30.6199791Z configure: creating ./config.status
2024-07-21T09:16:31.1506496Z config.status: creating src/gmpcompat.h
2024-07-21T09:16:31.1650486Z config.status: creating src/fft_tuning.h
2024-07-21T09:16:31.1795119Z config.status: creating src/fmpz/fmpz.c
2024-07-21T09:16:31.1943295Z config.status: creating Makefile
2024-07-21T09:16:31.2067669Z config.status: creating flint.pc
2024-07-21T09:16:31.2178980Z config.status: creating src/flint.h
2024-07-21T09:16:31.2332443Z config.status: creating src/config.h
2024-07-21T09:16:31.2446108Z config.status: creating src/flint-config.h
2024-07-21T09:16:31.2552061Z config.status: executing libtool commands
```

</details>

**Comment by oscarbenjamin** [comment]
> I do not understand the `ImportError`

What is `__FLINT_RELEASE` set to in the nightly release? In fact what is the nightly release?

**Comment by albinahlback** [comment]
> With this PR: [flintlib/python-flint#166](https://github.com/flintlib/python-flint/pull/166). The PR sets `--host=x86_64-pc-linux-gnu` passing the same value as used for building GMP: https://github.com/flintlib/python-flint/blob/2e4b0ab69b711a4d56e8cd8805b7220876ba611e/bin/cibw_before_all_linux.sh#L6 It also sets `--disable-assembly`, `--disable-avx2` and `--disable-avx512`.

Temporarily, you should push `--disable-arch`, but in the main branch it is deprecated and replaced by `--host` (where we extend GMP).

**Comment by oscarbenjamin** [comment]
Thanks Albin.

So if I understand correctly then for Flint 3.1 it is necessary to set `--disable-arch`. For Flint 3.2 it should be sufficient to specify `--host` and then we won't need to set `--disable-arch` any of the other `--disable-assembly`, `--disable-avx2`, `--disable-avx512` options?

**Comment by edgarcosta** [comment]
> > I do not understand the `ImportError`
> 
> What is `__FLINT_RELEASE` set to in the nightly release? In fact what is the nightly release?

Ignore this issue.

[nightly](https://github.com/flintlib/flint/releases) is just `main` already bootstrapped, but I now realized that I downloaded the "source" not the tarball, which for some reason points to very old code:

**Comment by albinahlback** [comment]
> So if I understand correctly then for Flint 3.1 it is necessary to set `--disable-arch`. For Flint 3.2 it should be sufficient to specify `--host` and then we won't need to set `--disable-arch` any of the other `--disable-assembly`, `--disable-avx2`, `--disable-avx512` options?

Correct.

**Pull request merged**
