### PR TITLE
Assert non-executable stack for assembly files

### PR DESCRIPTION
**Pull request by albinahlback**
Some GNU linkers do not set the stack as non-executable when the `.note.GNU-stack` section is missing.

Solves #2075. @mezzarobba

### CODE REVIEW

**Comment by albinahlback** [comment]
Clang yields warnings for this, and also for other things when compiling assembly files. Will fix this before merging this.

**Comment by mezzarobba** [comment]
I still get the warnings:
```
/usr/bin/ld: warning: build/mpn_extras/x86_64/broadwell/sqrhigh_normalised_hard.lo: missing .note.GNU-stack section implies executable stack
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
Building libflint.so.20.0.0
/usr/bin/ld: warning: build/mpn_extras_merged.lo: requires executable stack (because the .note.GNU-stack section is executable)
~/co/flint:noexecstack$
```

**Comment by albinahlback** [comment]
Hmm, I'll look into it. Thanks for taking the time.

**Comment by albinahlback** [comment]
This change yields different binaries compared to earlier for both GCC and Clang, which I suppose implies a now non-executable stack. This should work, and is what GMP does.

**Pull request merged**
