### PR TITLE
Optimize

### PR DESCRIPTION
**Pull request by albinahlback**

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
This doesn't look fully formed.

* ``-g`` shouldn't be removed as a default flag

* removes ``-funroll-loops`` even for those modules which benefit from it.

* It looks useful to be able to toggle optimization levels for individual files, but I wonder if it shouldn't be done on a module basis first. It's a lot of boilerplate to add these macros to each file, and if you want to experiment with optimization settings on a module basis, you have a lot of individual places in the code to edit. So it seems more logical to start with a list of modules with different optimization settings in the build system.

* Will these optimization settings be respected by non-GCC compilers?

* A single loop index is normally called ``i`` unless there is some need to disambiguate. I don't think there is anything to disambiguate for a trivial loop over a single vector. There's no better or worse convention here, just a question of trying to maintain consistency with other FLINT code.

**Comment by albinahlback** [comment]
> This doesn't look fully formed.
> 
>     * `-g` shouldn't be removed as a default flag
> 
>     * removes `-funroll-loops` even for those modules which benefit from it.

Alright.

>     * It looks useful to be able to toggle optimization levels for individual files, but I wonder if it shouldn't be done on a module basis first. It's a lot of boilerplate to add these macros to each file, and if you want to experiment with optimization settings on a module basis, you have a lot of individual places in the code to edit. So it seems more logical to start with a list of modules with different optimization settings in the build system.

Yeah, but this is just done for those functions known to really benefit from it. I believe that basically no other function in `nmod_vec` benefits from `-O3` as they are not really vectorizable (apart from a small part in `nmod_vec_scalar_mul_shoup`).

>     * Will these optimization settings be respected by non-GCC compilers?

You mean the manually set ones? No. But then, non-GCC compilers do not perform as well, so one should not expect performant code without them. I believe that Intel's compiler support `__GNUC__` as it is currently based on LLVM, but I am currently checking whether this is the case.

>     * A single loop index is normally called `i` unless there is some need to disambiguate. I don't think there is anything to disambiguate for a trivial loop over a single vector. There's no better or worse convention here, just a question of trying to maintain consistency with other FLINT code.

Ah, yeah, I can reverse this. This is just a leftover from implementing the fast version `_nmod_vec_add_fast`.

**Comment by albinahlback** [comment]
Yes, Intel's compiler defines `__GNUC__`.

**Comment by fredrik-johansson** [comment]
I would expect that ``add``, ``sub`` and ``neg`` all benefit the same?

What about Clang? I'm curious how its optimizer performs here.

**Comment by fredrik-johansson** [comment]
BTW, did you check the profiler output for all lengths 1-10, say? I wonder if the O3 code ever performs worse for short vectors.

**Comment by albinahlback** [comment]
> I would expect that `add`, `sub` and `neg` all benefit the same?

Yes, they would.

> What about Clang? I'm curious how its optimizer performs here.

I would suspect that Clang would have the same benefit, or maybe that even `-O2` is enough to generate the same output. I believe that GCC tends to be more conservative when it comes to optimizing.

> BTW, did you check the profiler output for all lengths 1-10, say? I wonder if the O3 code ever performs worse for short vectors.

Looking at the assembler output, it does look like it could perform worse when the length is smaller than 4 for AVX2 and 8 for AVX512. However, as you can see [here](https://github.com/flintlib/flint2/issues/1323#issuecomment-1484207012), that was not the case. I suppose `-O3` optimized some branch-loop-whatever, so that even the smaller case had benefits.

**Pull request closed without merging**
