### PR TITLE
add fmpq_mat vector products

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by wbhart** [comment]
This looks ok. I guess there's no speedups planned for the case when all the coefficients are small?

I'm happy to merge this if you are happy with it now.

**Comment by tthsqe12** [comment]
I don't plan on speeding those up at the moment.

**Comment by wbhart** [comment]
And you are happy for this to be merged now?

**Comment by tthsqe12** [comment]
sure

**Pull request merged**
