### PR TITLE
Adding some basic degree, set, trunc, equal functionalities for `nmod_poly_mat`

### PR DESCRIPTION
**Pull request by vneiger**
This adds some useful functions, along with test files, for `nmod_poly_mat`:
- getting the degree (directly calls existing `max_length`)
- `nmod_poly_mat_set_nmod_mat` : to set a poly_mat from an nmod_mat
- truncate and set_trunc
- left and right shifts (multiplication by ``x**k`` or ``x**(-k)``)
- getting or setting the "matrix coefficient" of a given degree (seeing the poly_mat as a polynomial with matrix coefficients)
- testing equality with an `nmod_mat`

The documentation of these new functions will follow.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
This is ready to merge?

**Comment by vneiger** [comment]
> This is ready to merge?

Now it should be (pending CI).

**Comment by vneiger** [comment]
Maybe some insight could be useful on the added ``nmod_poly_equal_ui``. In the present version, it assumes the input integer is already reduced modulo the polynomial's modulus, which is not consistent with e.g. `nmod_poly_set_coeff_ui`. If that's an issue, that could become two versions, ``_nmod_poly_equal_ui`` which is the current one and ``nmod_poly_equal_ui`` which first reduces the input limb and then calls the former.

**Comment by fredrik-johansson** [comment]
> Maybe some insight could be useful on the added nmod_poly_equal_ui.

Right, I think the current function should actually be called ``nmod_poly_equal_nmod``.

You could then have ``nmod_poly_equal_ui`` which just does ``nmod_poly_equal_nmod(poly, nmod_set_ui(x, mod))``.

**Comment by vneiger** [comment]
Thanks for the input. Fixed as suggested.

**Pull request merged**
