### PR TITLE
Generate and Install CMake configuration files

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Help to find flint with cmake `find_package(flint)` and link to it directly `target_ling_libraries(target flint::flint)`

### CODE REVIEW

**Comment by albinahlback** [comment]
Can you give me a script that shows me that it indeed works as intended? We usually do not use CMake as it mainly exists to give Windows users a native way to install FLINT.

**Comment by MehdiChinoune** [comment]
> Can you give me a script that shows me that it indeed works as intended?

```
cmake_minimum_required(VERSION 3.16)
project(test CXX)

add_executable(main main.cpp)

find_package(flint CONFIG)

target_link_libraries(main flint::flint)
```

> We usually do not use CMake as it mainly exists to give Windows users a native way to install FLINT.

CMake is a cross-platform tool and could be used anywhere.

**Comment by albinahlback** [comment]
> CMake is a cross-platform tool and could be used anywhere.

Yes, but it also has to be configured work properly. Currently our Autotools-system is more mature, which is why we do not recommend CMake unless you are a Windows user.

**Comment by albinahlback** [comment]
> I am a Windows user but using it on MinGW-w64 (MSYS2) where we could use autotools. CMake has a better support for Windows and It's easy to use and configure. My projects use CMake so I prefer a better support for CMake.

Look, I am very aware that many people may prefer CMake, Meson or whatever over Autotools. They are great tools, no question about that.

However, the reason why we use Autotools is because it is very hackable -- it is basically a shellscript with extra functionalities. It is also the standard in field -- check GMP, MPFR, GAP, FFTW, msolve, etc. They all use Autotools.

Now, of course it would be nice if our CMake script was full-fledged, but it is not. The reason being that very few uses it, which reflects upon amount of attention it gets.

**Comment by MehdiChinoune** [comment]
> Look, I am very aware that many people may prefer CMake, Meson or whatever over Autotools. They are great tools, no question about that.
> 
> However, the reason why we use Autotools is because it is very hackable -- it is basically a shellscript with extra functionalities.

I am a packager in MSYS2, autotools (especially libtool) is a nightmare.

>It is also the standard in field -- check GMP, MPFR, GAP, FFTW, msolve, etc. They all use Autotools.

All of those projects were founded before CMake and meson, no wonder they are using autotools.
LLVM moved to CMake a long time ago. GNOME projects moved to meson, Qt moved to CMake with Qt6...
xz now recommends using CMake..
I don't know which field are you talking about. Generally projects founded in 90s and 2000s use autotools because at the time autotools was the best one. Now with CMake and meson I always wonder why someone choose autotools.
I know you have no experience with CMake, so you don't how good It is. I recommend you to start using It's a great tool. It's hackable once you learn Its easy language.

> Now, of course it would be nice if our CMake script was full-fledged, but it is not. The reason being that very few uses it, which reflects upon amount of attention it gets.

I could work on that when I have time.

**Comment by eli-schwartz** [comment]
IMHO this PR is fairly risky as people will see that on Windows with cmake it produces a set of CMake configuration files, then write their own projects which try to detect flint using `find_package(flint)` and that will then fail when flint has been installed via autotools.

@MehdiChinoune Is there some way to install these CMake configuration files in the autotools build too, or is this just inevitable to be an unpredictable difference between the two build systems?

**Comment by MehdiChinoune** [comment]
I don't any way to generate them using autotools.

**Pull request merged**
