### PR TITLE
[WIP] basecase for flint_mpn_mul and flint_mpn_mul_n

### PR DESCRIPTION
**Pull request by fredrik-johansson**
It appears that we can do better than GMP's basecase multiplication using a codelet approach (so there is no loop overhead) and by doing columnwise updates (i.e. dot products) instead of rowwise updates (i.e. addmul_1's).

On my laptop (Zen3), I get timings like this:

```
     mpn_mul_n   flint_mpn_mul_n  speedup
n = 1    3.98e-09    2.13e-09   1.869x
n = 2    4.92e-09    2.38e-09   2.067x
n = 3    7.93e-09    4.04e-09   1.963x
n = 4    1.21e-08    7.32e-09   1.653x
n = 5    1.62e-08    1.17e-08   1.385x
n = 6    2.37e-08    1.77e-08   1.339x
n = 7    2.92e-08    2.52e-08   1.159x
n = 8    3.68e-08    3.02e-08   1.219x
n = 9    4.57e-08    3.78e-08   1.209x
n = 10    5.82e-08    4.72e-08   1.233x
n = 11    6.65e-08    5.73e-08   1.161x
n = 12    7.82e-08    6.64e-08   1.178x
n = 13    9.05e-08    9.16e-08   0.988x
n = 14    1.11e-07    1.1e-07   1.009x
n = 15    1.21e-07    1.22e-07   0.992x
```

This is a WIP because we need to confirm that this isn't massively slower on other architectures, for which we should put in some logic to fall back to ``mpn_mul_n``.

The speedup seems to persist up to n = 20 or so but I've only done up to n = 12 here since i-cache misses might become an issue. I'm hoping that slightly bigger sizes and unbalanced multiplications can be done as efficiently using a block strategy (e.g. 16x16 using four 8x8 products). Codelets + Karatsuba should do well eventually too.

Squaring and unbalanced multiplications to be done later. The macros and inline fixed-size multiplications should also later be exported to ``mpn_extras.h`` since they would be useful in various places (fully inlining a fixed-sized multiplication in the calling code will give further speedups).

### CODE REVIEW

**Comment by albinahlback** [comment]
Looks really nice!

I suppose you used GCC to benchmark? In that case we should really want to optimize `longlong.h` as (IIRC) GMP bases its `mpn_mul_basecase` off of assembly for a lot of processors, and this code should only perform better if `add_ssaaa` and friends are somewhat optimal.

**Comment by fredrik-johansson** [comment]
OK, so here is what's going on (thanks to Dan for some feedback).

GMP's inner loops do 2 adds for each mul in the addmul_1 loop. This is possible thanks to the mulx/adox/adcx instructions which allow maintaining two separate carry chains.

The dot product method does 3 adds for each mul which is asymptotically slower, so basically all the speedup comes from avoiding loop overhead.

[This project](https://github.com/krisk0/broadwell_multiplication) has some fixed-size asm routines based on the mulx/adox/adcx method. Timing comparison for 8x8:

    mpn_mul_n    flint_mpn_mul_8       mul8_zen
    3.64e-08        2.96e-08           2.71e-08

So that would give us another 10% speedup. I don't see how to produce that kind of code from C except by using huge blocks of inline assembly though.

I'm thinking we should really bite the bullet and write our own assembly code generator for basic mpn routines. We can't use the one I just linked to, because it's LGPL3, unfortunately. 

Anyway, the code in this PR could perhaps be a decent intermediate solution.

We could perhaps do a bit better by playing Tetris with the partial products and doing fewer, wider multi-limb additions, but that's going to get ugly...

**Comment by fredrik-johansson** [comment]
Now using basecases for both `flint_mpn_mul` and `flint_mpn_mul_n`.

Current results for `flint_mpn_mul_n`:

```
n = 1    3.92e-09    2.34e-09   1.675x
n = 2    4.63e-09    2.35e-09   1.970x
n = 3    7.85e-09    3.87e-09   2.028x
n = 4    1.19e-08    7.19e-09   1.655x
n = 5    1.58e-08    1.13e-08   1.398x
n = 6    2.35e-08    1.67e-08   1.407x
n = 7    2.87e-08    2.27e-08   1.264x
n = 8    3.61e-08    2.98e-08   1.211x
n = 9    4.48e-08    3.73e-08   1.201x
n = 10    5.72e-08    4.62e-08   1.238x
n = 11    6.55e-08    5.58e-08   1.174x
n = 12    7.69e-08    6.5e-08   1.183x
n = 13    8.9e-08    8.99e-08   0.990x
n = 14    1.07e-07    1.08e-07   0.991x
n = 15    1.19e-07    1.2e-07   0.992x
n = 16    1.34e-07    1.34e-07   1.000x
n = 17    1.5e-07    1.5e-07   1.000x
n = 18    1.74e-07    1.75e-07   0.994x
n = 19    1.83e-07    1.9e-07   0.963x
n = 20    1.95e-07    2.01e-07   0.970x
```

Current results for `flint_mpn_mul` (speedups vs `mpn_mul`):

```
n = 1    1.148x  
n = 2    1.642x  1.764x  
n = 3    1.436x  1.694x  1.638x  
n = 4    1.631x  1.762x  1.596x  1.493x  
n = 5    1.348x  1.623x  1.434x  1.359x  1.310x  
n = 6    1.583x  1.594x  1.464x  1.405x  1.314x  1.311x  
n = 7    1.621x  1.465x  1.387x  1.262x  1.244x  1.209x  1.218x  
n = 8    1.608x  1.499x  1.333x  1.235x  1.230x  1.186x  1.167x  1.168x  
n = 9    1.612x  1.388x  1.272x  1.210x  1.167x  1.172x  1.153x  1.169x  1.188x  
n = 10    1.682x  1.340x  1.291x  1.218x  1.235x  1.212x  1.211x  1.228x  1.237x  1.205x  
n = 11    1.194x  0.925x  0.954x  0.960x  0.967x  0.969x  0.973x  0.978x  0.977x  0.984x  1.150x  
n = 12    1.157x  0.931x  0.949x  0.959x  0.969x  0.974x  0.977x  0.980x  0.980x  0.982x  0.983x  1.172x  
n = 13    1.159x  0.933x  0.955x  0.961x  0.963x  0.973x  0.978x  0.986x  0.984x  0.984x  0.979x  0.992x  0.977x  
n = 14    1.155x  0.942x  0.963x  0.965x  0.974x  0.976x  0.977x  0.984x  0.985x  0.990x  0.988x  0.987x  0.990x  0.982x  
n = 15    1.155x  0.944x  0.956x  0.969x  0.974x  0.978x  0.983x  0.983x  0.984x  0.985x  0.987x  0.987x  0.981x  0.991x  0.983x  
n = 16    1.124x  0.944x  0.966x  0.968x  0.976x  0.978x  0.984x  0.984x  0.987x  0.987x  0.986x  0.990x  0.991x  1.000x  0.984x  0.993x  
```

I've put in code for all unbalanced multiplications up to n = 10. We could clearly go even farther, especially for nx1 and nx2 products. Though first I'd like to see some results on macrobenchmarks, and on other machines...

The dispatch is now done by looking up a function in a table of function pointers. We could even consider defining ``flint_mpn_mul`` and ``flint_mpn_mul_n`` as inline functions so that there is even less overhead jumping into the right subroutine.

**Comment by fredrik-johansson** [comment]
It's difficult to find examples where this really makes a difference.

I believe this is because we already try hard to avoid doing few-word integer operations, early on switching to KS multiplication for polynomials and so on, and where we do lots of few-limb multiplications, e.g. for arb, there is a lot of overhead around each call to ``mpn_mul`` anyway. A couple of Arb examples which do see a tiny speedup:

```build/examples/hilbert_matrix 120```

Old: 0.51 seconds
New: 0.47 seconds

```build/examples/poly_roots w 100```

Old: 1.42 seconds
New: 1.29 seconds

Of course, my intention is to rewrite much of the basic arb arithmetic to use truncating multiplications and to remove as much as the remaining overhead as possible, which should give bigger improvements...

**Comment by fredrik-johansson** [comment]
I have some timings on other machines now.

gcc (Debian 10.2.1-6), Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz

    n = 1    7.75e-09    3.47e-09   2.233x
    n = 2    1.12e-08    4.67e-09   2.398x
    n = 3    1.66e-08    9.83e-09   1.689x
    n = 4    2.2e-08    1.66e-08   1.325x
    n = 5    3.25e-08    2.53e-08   1.285x
    n = 6    4.39e-08    3.67e-08   1.196x
    n = 7    5.98e-08    4.97e-08   1.203x
    n = 8    7.47e-08    6.39e-08   1.169x
    n = 9    9.65e-08    8.35e-08   1.156x
    n = 10    1.18e-07    1.05e-07   1.124x
    n = 11    1.44e-07    1.32e-07   1.091x
    n = 12    1.7e-07    1.62e-07   1.049x
    n = 13    2e-07    2.03e-07   0.985x
    n = 1    1.727x  
    n = 2    2.217x  2.082x  
    n = 3    1.646x  1.494x  1.475x  
    n = 4    1.449x  1.367x  1.302x  1.228x  
    n = 5    1.628x  1.279x  1.303x  1.176x  1.205x  
    n = 6    1.527x  1.243x  1.262x  1.158x  1.223x  1.152x  
    n = 7    1.498x  1.187x  1.248x  1.146x  1.182x  1.157x  1.168x  
    n = 8    1.364x  1.152x  1.200x  1.132x  1.145x  1.124x  1.154x  1.075x  
    n = 9    1.398x  1.178x  1.166x  1.132x  1.145x  1.117x  1.112x  1.138x  1.107x  
    n = 10    1.397x  1.131x  1.195x  1.140x  1.180x  1.138x  1.174x  1.095x  1.138x  1.017x  
    n = 11    1.107x  0.926x  0.973x  0.957x  0.977x  0.972x  0.989x  0.991x  1.000x  0.985x  1.083x  
    n = 12    1.106x  0.948x  0.956x  0.970x  0.972x  0.981x  0.981x  0.991x  0.985x  0.986x  0.987x  1.006x  

The speedup on Intel is a bit smaller than on AMD, but there is still a speedup. So far so good.

Same machine with clang 11.0.1-2

    n = 1    8.1e-09    4.63e-09   1.749x
    n = 2    1.16e-08    7.71e-09   1.505x
    n = 3    1.69e-08    1.88e-08   0.899x
    n = 4    2.24e-08    3.21e-08   0.698x
    n = 5    3.27e-08    4.91e-08   0.666x
    n = 6    4.39e-08    6.98e-08   0.629x
    n = 7    5.97e-08    9.43e-08   0.633x
    n = 8    7.5e-08    1.23e-07   0.610x
    n = 9    9.48e-08    1.54e-07   0.616x
    n = 10    1.17e-07    1.91e-07   0.613x
    n = 11    1.42e-07    2.3e-07   0.617x
    n = 12    1.68e-07    2.74e-07   0.613x
    n = 13    1.98e-07    1.98e-07   1.000x
    n = 1    1.374x  
    n = 2    1.804x  1.325x  
    n = 3    1.149x  0.856x  0.803x  
    n = 4    1.038x  0.753x  0.715x  0.662x  
    n = 5    1.058x  0.711x  0.694x  0.640x  0.650x  
    n = 6    0.956x  0.662x  0.690x  0.636x  0.651x  0.618x  
    n = 7    0.875x  0.643x  0.691x  0.625x  0.641x  0.612x  0.639x  
    n = 8    0.802x  0.628x  0.649x  0.616x  0.630x  0.612x  0.616x  0.611x  
    n = 9    0.835x  0.634x  0.638x  0.615x  0.622x  0.607x  0.618x  0.608x  0.617x  
    n = 10    0.783x  0.626x  0.662x  0.620x  0.646x  0.621x  0.632x  0.615x  0.632x  0.620x  
    n = 11    1.067x  0.929x  0.987x  0.959x  0.977x  0.975x  0.968x  0.981x  0.992x  0.977x  0.615x  
    n = 12    1.105x  0.945x  0.966x  0.964x  1.000x  0.968x  0.990x  0.983x  0.992x  0.986x  0.987x  0.608x  

Hopefully this will be fixed with better longlong.h for clang.

Apple Icestorm-M1 + Firestorm-M1, gcc (Debian 13.2.0-7):

    n = 1    4.69e-09    1.64e-09   2.860x
    n = 2    6.16e-09    6.05e-09   1.018x
    n = 3    1e-08    1.58e-08   0.633x
    n = 4    1.34e-08    2.99e-08   0.448x
    n = 5    1.9e-08    4.88e-08   0.389x
    n = 6    2.33e-08    7.17e-08   0.325x
    n = 7    3.1e-08    1e-07   0.310x
    n = 8    3.75e-08    1.31e-07   0.286x
    n = 9    4.52e-08    1.68e-07   0.269x
    n = 10    5.15e-08    2.09e-07   0.246x
    n = 11    5.96e-08    2.54e-07   0.235x
    n = 12    7.58e-08    3.08e-07   0.246x
    n = 13    8.29e-08    8.49e-08   0.976x
    n = 1    1.934x  
    n = 2    1.615x  1.040x  
    n = 3    1.168x  0.675x  0.622x  
    n = 4    0.830x  0.525x  0.486x  0.448x  
    n = 5    0.706x  0.431x  0.375x  0.371x  0.362x  
    n = 6    0.612x  0.380x  0.365x  0.345x  0.338x  0.358x  
    n = 7    0.560x  0.338x  0.342x  0.318x  0.307x  0.326x  0.284x  
    n = 8    0.502x  0.311x  0.281x  0.275x  0.268x  0.263x  0.273x  0.288x  
    n = 9    0.467x  0.289x  0.266x  0.265x  0.261x  0.262x  0.274x  0.268x  0.275x  
    n = 10    0.417x  0.270x  0.245x  0.244x  0.252x  0.245x  0.251x  0.263x  0.244x  0.245x  
    n = 11    1.434x  0.930x  0.955x  0.969x  1.018x  1.018x  1.013x  0.996x  1.040x  0.986x  0.241x  
    n = 12    1.447x  0.908x  0.930x  0.959x  0.963x  1.036x  0.970x  0.974x  0.969x  0.971x  0.969x  0.247x  

Same machine if I define ``__aarch64__``:

    n = 1    4.72e-09    1.39e-09   3.396x
    n = 2    6.42e-09    1.86e-09   3.452x
    n = 3    1.01e-08    3.99e-09   2.531x
    n = 4    1.35e-08    6.76e-09   1.997x
    n = 5    1.92e-08    1.08e-08   1.778x
    n = 6    2.2e-08    1.68e-08   1.310x
    n = 7    3.02e-08    2.43e-08   1.243x
    n = 8    3.74e-08    3.3e-08   1.133x
    n = 9    4.46e-08    4.35e-08   1.025x
    n = 10    5.15e-08    5.31e-08   0.970x
    n = 11    6.07e-08    6.49e-08   0.935x
    n = 12    7.68e-08    8.01e-08   0.959x
    n = 13    8.28e-08    8.49e-08   0.975x
    n = 1    2.463x  
    n = 2    2.649x  2.754x  
    n = 3    2.226x  1.953x  2.328x  
    n = 4    1.830x  1.747x  2.040x  1.991x  
    n = 5    1.733x  1.614x  1.687x  1.582x  1.591x  
    n = 6    1.693x  1.547x  1.693x  1.533x  1.613x  1.523x  
    n = 7    1.636x  1.489x  1.421x  1.400x  1.292x  1.199x  1.310x  
    n = 8    1.610x  1.385x  1.264x  1.128x  1.108x  1.064x  1.087x  1.132x  
    n = 9    1.571x  1.304x  1.151x  1.097x  1.106x  1.040x  1.085x  1.042x  1.095x  
    n = 10    1.456x  1.211x  1.095x  1.037x  1.000x  0.957x  0.989x  0.958x  0.996x  0.974x  
    n = 11    1.474x  0.943x  0.932x  0.942x  0.970x  0.969x  0.963x  0.963x  1.024x  0.989x  0.918x  
    n = 12    1.474x  0.893x  0.924x  0.945x  0.953x  0.958x  0.978x  0.973x  0.954x  0.965x  0.983x  0.948x  

That also looks good. nxn multiply is faster only up to n = 9 but that's not a big problem.

**Comment by albinahlback** [comment]
Fredrik, do you still have access to the Apple M1? If so, can you redo the test with Clang using the new longlong.h?

**Comment by fredrik-johansson** [comment]
Clang (16.0.6) produces assembly that looks like this:

```
$ gdb -batch -ex 'file libflint.so' -ex 'disassemble flint_mpn_mul_3x3'
Dump of assembler code for function flint_mpn_mul_3x3:
   0x0000000000147574 <+0>:	ldr	x8, [x1]
   0x0000000000147578 <+4>:	ldr	x9, [x2]
   0x000000000014757c <+8>:	mul	x10, x9, x8
   0x0000000000147580 <+12>:	umulh	x8, x9, x8
   0x0000000000147584 <+16>:	str	x10, [x0]
   0x0000000000147588 <+20>:	ldp	x9, x10, [x2]
   0x000000000014758c <+24>:	ldp	x11, x12, [x1]
   0x0000000000147590 <+28>:	umulh	x13, x10, x11
   0x0000000000147594 <+32>:	mul	x10, x10, x11
   0x0000000000147598 <+36>:	mul	x11, x9, x12
   0x000000000014759c <+40>:	adds	x8, x8, x10
   0x00000000001475a0 <+44>:	umulh	x9, x9, x12
   0x00000000001475a4 <+48>:	cinc	x10, x13, cs	// cs = hs, nlast
   0x00000000001475a8 <+52>:	adds	x8, x8, x11
   0x00000000001475ac <+56>:	adcs	x9, x10, x9
   0x00000000001475b0 <+60>:	str	x8, [x0, #8]
   0x00000000001475b4 <+64>:	ldp	x11, x12, [x1]
   0x00000000001475b8 <+68>:	ldr	x8, [x2, #16]
   0x00000000001475bc <+72>:	mul	x13, x8, x11
   0x00000000001475c0 <+76>:	umulh	x8, x8, x11
   0x00000000001475c4 <+80>:	ldp	x10, x11, [x2]
   0x00000000001475c8 <+84>:	cinc	x8, x8, cs	// cs = hs, nlast
   0x00000000001475cc <+88>:	adds	x9, x9, x13
   0x00000000001475d0 <+92>:	adcs	x8, x8, xzr
   0x00000000001475d4 <+96>:	mrs	x14, nzcv
   0x00000000001475d8 <+100>:	mul	x13, x11, x12
   0x00000000001475dc <+104>:	umulh	x11, x11, x12
   0x00000000001475e0 <+108>:	ldr	x12, [x1, #16]
   0x00000000001475e4 <+112>:	adds	x9, x9, x13
   0x00000000001475e8 <+116>:	adcs	x8, x8, x11
   0x00000000001475ec <+120>:	mul	x13, x10, x12
   0x00000000001475f0 <+124>:	cset	w11, cs	// cs = hs, nlast
   0x00000000001475f4 <+128>:	msr	nzcv, x14
   0x00000000001475f8 <+132>:	cinc	x11, x11, cs	// cs = hs, nlast
   0x00000000001475fc <+136>:	adds	x9, x9, x13
   0x0000000000147600 <+140>:	umulh	x10, x10, x12
   0x0000000000147604 <+144>:	adcs	x8, x8, x10
   0x0000000000147608 <+148>:	str	x9, [x0, #16]
   0x000000000014760c <+152>:	cinc	x11, x11, cs	// cs = hs, nlast
   0x0000000000147610 <+156>:	ldp	x14, x9, [x2, #8]
   0x0000000000147614 <+160>:	ldp	x13, x12, [x1, #8]
   0x0000000000147618 <+164>:	mul	x10, x9, x13
   0x000000000014761c <+168>:	umulh	x9, x9, x13
   0x0000000000147620 <+172>:	adds	x8, x8, x10
   0x0000000000147624 <+176>:	mul	x10, x14, x12
   0x0000000000147628 <+180>:	adcs	x9, x11, x9
   0x000000000014762c <+184>:	umulh	x12, x14, x12
   0x0000000000147630 <+188>:	cset	w11, cs	// cs = hs, nlast
   0x0000000000147634 <+192>:	adds	x8, x8, x10
   0x0000000000147638 <+196>:	adcs	x9, x9, x12
   0x000000000014763c <+200>:	str	x8, [x0, #24]
   0x0000000000147640 <+204>:	ldr	x8, [x1, #16]
   0x0000000000147644 <+208>:	ldr	x10, [x2, #16]
   0x0000000000147648 <+212>:	mul	x13, x10, x8
   0x000000000014764c <+216>:	umulh	x8, x10, x8
   0x0000000000147650 <+220>:	cinc	x10, x11, cs	// cs = hs, nlast
   0x0000000000147654 <+224>:	adds	x9, x9, x13
   0x0000000000147658 <+228>:	adc	x8, x10, x8
   0x000000000014765c <+232>:	stp	x9, x8, [x0, #32]
   0x0000000000147660 <+236>:	ret
End of assembler dump.
```

The assembly is quite different, but the timings look almost identical.

**Comment by fredrik-johansson** [comment]
> Alright! I doubt it is worth implementing our own assembly code for ARM.

Well, GMP is still faster asymptotically, so it should be better to do whatever they are doing, just unrolled.

But x86_64 is a more important target at the moment.

**Comment by albinahlback** [comment]
> Well, GMP is still faster asymptotically, so it should be better to do whatever they are doing, just unrolled.

Is it the `cinc` that you refer to?

**Pull request closed without merging**
