### PR TITLE
Fix substitution of version number for older autotools

### PR DESCRIPTION
**Pull request by albinahlback**
Before I had this problem:
```
./configure: line 17875: 3.1.0-dev=3.1.0-dev: command not found
```
Seems like it is fine with newer versions, but my system does not like it.

### CODE REVIEW

**Comment by fingolfin** [comment]
Which version of autoconf and m4 produces the error?

**Comment by albinahlback** [comment]
M4 version 1.4.18 and Autoconf 2.69.

**Comment by albinahlback** [comment]
@fingolfin Let me know if you have any complaints or not. If you do not, I will merge. :-)

**Comment by fingolfin** [comment]
To be clear, I have no objections to merging this if it fixes a concrete bug! But it's really weird that this is breaking in this way, esp. since this patch even *removes* M4 quoting (i.e. `[FLINT_VERSION]` is changed to the unquoted `FLINT_VERSION_FULL`). So I'd like to understand it. But me wanting to understand it should not block a fix -- if I ever understand it and see a "better" fix I can just submit a PR of my own :-)

**Review by fingolfin — APPROVED** [review]

**Comment by albinahlback** [comment]
> To be clear, I have no objections to merging this if it fixes a concrete bug! But it's really weird that this is breaking in this way, esp. since this patch even _removes_ M4 quoting (i.e. `[FLINT_VERSION]` is changed to the unquoted `FLINT_VERSION_FULL`). So I'd like to understand it. But me wanting to understand it should not block a fix -- if I ever understand it and see a "better" fix I can just submit a PR of my own :-)

Yeah, I tried with double quoting, i.e. `[[FLINT_VERSION]]`, as well, but it didn't work...

**Comment by fredrik-johansson** [comment]
Is this worth merging into the 3.0 branch for a future 3.0.1 patch release?

**Comment by albinahlback** [comment]
> Is this worth merging into the 3.0 branch for a future 3.0.1 patch release?

Yeah, I think so

**Comment by fredrik-johansson** [comment]
OK, done.

**Pull request merged**
