### PR TITLE
Add CMake options to enable AVX* instructions

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by albinahlback** [comment]
Looks to me like it no longer autodetects whether AVX2 is available.

**Comment by MehdiChinoune** [comment]
> Looks to me like it no longer autodetects whether AVX2 is available.

That's exactly what autoconf is doing, It doesn't enable avx2 unless '--enable-avx' is passed.

**Comment by albinahlback** [comment]
It actually does check if AVX2 is enabled if system is x86_64: https://github.com/flintlib/flint/blob/main/acinclude.m4#L383

It will not, as you correctly point out, push `-mavx2` to the compiler unless `--enable-avx2` is set.

**Comment by MehdiChinoune** [comment]
Is there something I should do about this PR?

**Comment by albinahlback** [comment]
Ah yes, sorry for being unclear.

CMake should set `-march=native` (and something sort of equivalent for MSVC) by default. Then it should detect whether AVX2 or NEON is available. This is in order to enable the `fft_small` module by default on systems that can handle such instructions, as well as optimizing other parts of the library.

It would be nice with an opt-out for `-march=native`, and an opt-in for enabling AVX2 and NEON, which is what I think would be nice to do with this PR.

**Comment by MehdiChinoune** [comment]
`-march=native` is not suitable for packaging. I could add an option for it but disabled by default.

**Comment by albinahlback** [comment]
Look, this is what I think is the best way to ship the library. Package managers tend to have scripts that they follow, and once they are set there is little more to do. Moreover, they tend to be more experienced than the average user. Hence, I think the defaults should benefit the newcomers, who perhaps do not understand that `fft_small` utilizes certain instruction sets in order to outperform GMP (pretty drastically on AMD CPUs) and that this has to be set during the configuration, or that the current assembly code requires the ADX instruction set which also has to be specified.

And the build systems could be drastically better, even with the same outcome in mind. And people may disagree with how things are currently done, and perhaps they would prefer it your way; that's fine. And I am not made of stone, I am willing to have my opinions changed. But if you instist on being short and not giving explanations, or not even being somewhat nice for that matter, then don't expect me to change my mind.

**Comment by MehdiChinoune** [comment]
OK, I will make '-march=native' the default and add an option to disable it.
Altough '-mavx2' should be sufficient for x86_64 (I should search for theo one for aarch64). What do you think.

**Comment by albinahlback** [comment]
I think it sounds good to try setting `-march=native` by default, and having opt-out as an option. And I like the idea of being able to set `AVX2` without setting `-march` (distributions of Linux will soon start requiring x86_64-v3, no?).

Just note that for Clang and GCC enables NEON by default on ARM CPUs without setting `-march` (you can check via `echo | $CC -dM -E - | grep "__ARM_NEON"`), at least on newer versions of Clang and GCC. And I believe that `-march` does not work on Clang for macOS.

**Comment by fredrik-johansson** [comment]
There's also the use of ADX instructions.

**Comment by albinahlback** [comment]
> There's also the use of ADX instructions.

Yeah, but I haven't looked into how to translate GMP's assembly configuration to CMake.

**Comment by MehdiChinoune** [comment]
I have enabled `-mavx2` and `-march=native` enabled by default. This means that people with CPUs without AVX2 has to pass `-DENABLE_AVX2=OFF`.

**Comment by MehdiChinoune** [comment]
@albinahlback did you change your mind about `-march=native` in #1805?

**Comment by albinahlback** [comment]
> @albinahlback did you change your mind about `-march=native` in #1805?

No, I only added an option to opt-out of setting `-march` as well as pushing entry to `-march`.

**Comment by albinahlback** [comment]
Thanks!

**Pull request merged**
