### PR TITLE
Change #ifdef FLINT_WANT_ASSERT to #if FLINT_WANT_ASSERT

### PR DESCRIPTION
**Pull request by albinahlback**

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
I was wondering more generally why many config macros are checked with #ifdef, when #if seems more robust?

**Comment by dimpase** [comment]
How to deal with FLINT_ASSERT and FLINT_WANT_ASSERT in code that uses flint? It doesn't seem to be documented.
Does one have to add -D... to CFLAGS, or there is a better way? 

It seems that not passing any -D leads to errors, as
flint conditionally (on FLINT_WANT_ASSERT) includes headers with definitions of functions used in FLINT_ASSERT calls - but this is strange...

**Comment by albinahlback** [comment]
> How to deal with FLINT_ASSERT and FLINT_WANT_ASSERT in code that uses flint? It doesn't seem to be documented. Does one have to add -D... to CFLAGS, or there is a better way?
> 
> It seems that not passing any -D leads to errors, as flint conditionally (on FLINT_WANT_ASSERT) includes headers with definitions of functions used in FLINT_ASSERT calls - but this is strange...

You compile using `--enable-assert` to configure.

**Comment by dimpase** [comment]
Do you mean to say that if my code uses a usual autotools setup, I have to pass this to 
my `./configure`?

But, suppose I want a finer control, eg asserts only in my code?

**Comment by albinahlback** [comment]
> Do you mean to say that if my code uses a usual autotools setup, I have to pass this to my `./configure`?
> 
> But, suppose I want a finer control, eg asserts only in my code?

Sorry, perhaps I misunderstood your question. If you want to enable assertions *inside* of FLINT, you pass `--enable-assert` when configuring FLINT. If you only want assertions in *your* codebase (something outside the FLINT source code), you could either use `FLINT_ASSERT` or define your own macro.

Now, `FLINT_ASSERT` relies on the configuring process of FLINT, hence if you want to enable assertions inside *your* codebase while having assertions disabled inside FLINT, I would advise you to define your own macro.

**Comment by dimpase** [comment]
I built/installed flint (the current master) using cmake, without giving any options to cmake.

Now it appears that I still must pass something flint-specific in CFLAFS to get the code which uses it to compile.
Otherwise FLINT_ASSERT does not disregard its args, but FLINT_WANT_ASSERT is not set to allow inclusion of hearders for flint functions called in FLINT_ASSERTs.

Looks like a flint bug to me, not sure where. Naturally if flint asserts are on, the corresponding headers should get included.

**Comment by dimpase** [comment]
Autotools build on OpenBSD is broken, as usual, by incorrect calls to ldconfig and non-creation of the correct libflint.so* symlinks.

In this sense, cmake build works better, but now I have this snag with headers.

**Comment by albinahlback** [comment]
> I built/installed flint (the current master) using cmake, without giving any options to cmake.

We have started to advise users to not use CMake unless you use Windows. CMake is only present to give Windows users a native way to compile FLINT. It is not as refined as the Autotools-way. However, it is understandable that you use CMake as it appears to be broken for BSD-systems. I am currently trying to fix it.

> Now it appears that I still must pass something flint-specific in CFLAFS to get the code which uses it to compile. Otherwise FLINT_ASSERT does not disregard its args, but FLINT_WANT_ASSERT is not set to allow inclusion of hearders for flint functions called in FLINT_ASSERTs.

There was a bug for CMake in this PR which set `FLINT_ASSERT` to `assert` for CMake builds. This should now be fixed. But as I said, I think you should define your own macro.

> Autotools build on OpenBSD is broken, as usual, by incorrect calls to ldconfig and non-creation of the correct libflint.so* symlinks.

Yes, it does appear to be broken for non-FreeBSD BSD-systems. I am trying to fix this in https://github.com/flintlib/flint/pull/1735, but I haven't figured out how to fix it (I get some error about permissions).

**Pull request merged**
