### PR TITLE
fabs to FLINT_ABS

### PR DESCRIPTION
**Pull request by edgarcosta**
See https://en.cppreference.com/w/c/numeric/math/abs and https://en.cppreference.com/w/c/numeric/math/fabs

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
This looks like it will be wrong when ``slong`` is actually ``long long``. I think we should define our own inline function in ``flint.h`` or in ``long_extras.h`` for this.

**Comment by edgarcosta** [comment]
I have switched to FLINT_ABS

**Comment by edgarcosta** [comment]
I have added `slong_abs`, but now I wonder if `FLINT_ABS` should call `slong_abs`

**Comment by fredrik-johansson** [comment]
No need to change ``FLINT_ABS``.

However, I wonder if this change to avoid ``fabs`` is even desirable.

The advantage of casting the size multiplication in terms of ``double`` is that you avoid a potential overflow. This probably isn't going to happen on a 64-bit machine, but on a 32-bit machine you could have a 50000 vector with 50000 bit entries where the ``slong`` multiply overflows. Not that I know why anyone would actually do that on a 32-bit machine these days...

**Comment by edgarcosta** [comment]
Calling fabs is fine, but then we should explicitly cast it.

**Comment by fredrik-johansson** [comment]
Yeah, that makes sense.

**Pull request merged**
