### PR TITLE
Introduce `ca_types.h`, `gr_types.h` and `nf_types.h`

### PR DESCRIPTION
**Pull request by albinahlback**
Perhaps these headers should be split in some other ways. For instance, I pushed `qqbar_t` into `ca_types.h`, which perhaps is not the most fitting.

- Converted `WARN_UNUSED_RESULT` to `FLINT_WARN_UNUSED`.
- Reduced a lot of inclusions in headers.

A multithreaded build now takes around 2% less time to build than before.

Will squash when it seems to be okay.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Looks generally OK, but not sure about moving the ``qqbar`` and ``fexpr`` types which are really independent of the ``ca`` types.

**Comment by fredrik-johansson** [comment]
Also, ``nf_elem.h`` and ``nf.h`` aren't big files, nor widely included in other files. We could just as well keep the types there and de-inline the remaining inline functions in ``nf_elem.h`` to save on some bloat, I think.

**Comment by albinahlback** [comment]
Yeah, I agree. Perhaps group together the algebraic number theory stuff in some nice way, namely nf, qfb and qqbar?

**Comment by albinahlback** [comment]
Superseded by #1987

**Pull request closed without merging**
