### PR TITLE
New `flint_vfprintf` function

### PR DESCRIPTION
**Pull request by albinahlback**
Not sure why there was a lot of code duplication before with `flint_printf` and `flint_fprintf`, but this version should be faster due to less calls to `vprintf`, and allows printing of FLINT types.

Before thinking of merging, we should establish the printing format for all the types. One could have a compact version and a spacious version for printing (like `%{fmpz_mat,compact}` would signal compact printing, or whatever), but I think we should always print on a compact form (that is, one liners).

We also need to fix the return values for all printing functions for FLINT types. For instance, `fmpq_fprint` does not return the number of characters written to file stream in case the rational is not an integer.

Furthermore, I don't think we should use `flint_printf` for IO functions. This would work, but I would not like to have circular dependencies (such as `fmpz_fprint` relies on `flint_printf` relies on `fmpz_fprint` etc.).

Treats #1644 

Edit: We also need to create a test for this printing function.

### CODE REVIEW

**Comment by albinahlback** [comment]
To try this out, you can use this code:
```c
#include "flint/flint.h"
#include "flint/fmpz.h"
#include "flint/fmpz_vec.h"
#include "flint/fmpz_poly.h"

int
main()
{
    fmpz_t a, b;
    fmpz_poly_t p;
    slong len = 10;
    fmpz * vec;
    ulong x = 81728172312UL;
    FLINT_TEST_INIT(state);

    fmpz_init_set_ui(a, 1827123123123123123UL);
    fmpz_init_set(b, a);
    fmpz_mul_ui(b, a, 9189728187224UL);

    fmpz_poly_init(p);
    fmpz_poly_set_str(p, "6  1 1 1 10 5 1");

    vec = _fmpz_vec_init(len);
    _fmpz_vec_randtest(vec, state, len, 5);

    flint_printf(
            "This is a ulong\n  x = %wu\n\n"
            "And this is an fmpz\n  a = %{fmpz}\n\n"
            "And this is an fmpz_vec\n  vec = %{fmpz_vec}\n\n"
            "And this is an fmpz_poly\n  p = %{fmpz_poly}\n\n"
            "And this is another fmpz\n  b = %{fmpz}\n\n"
            "This is a slong\n  z = %wd\n",
            x,
            a,
            vec, len,
            p,
            b,
            -12387123L);

    fmpz_clear(a);
    fmpz_clear(b);
    fmpz_poly_clear(p);
    _fmpz_vec_clear(vec, len);

    FLINT_TEST_CLEANUP(state);

    return 0;
}
```
which prints
```
This is a ulong
  x = 81728172312

And this is an fmpz
  a = 1827123123123123123

And this is an fmpz_vec
  vec = 10  1 0 0 -7 27 1 0 -3 0 15

And this is an fmpz_poly
  p = x^5+5*x^4+10*x^3+x^2+x+1

And this is another fmpz
  b = 16790764866093311614484147580552

This is a slong
  z = -12387123
```

**Comment by albinahlback** [comment]
I would prefer if vectors were printed like
```
{len = LEN; [x_{1}, ..., x_{LEN}]}
```
or something similar, and matrices to be printed like
```
{r = ROWS, c = COLS; [[x_{1, 1}, ..., x_{1, c}] ... [x_{r, 1}, ..., x_{r, c}]]}
```

We also have to think of how to print Arb types (such as if one must specify the number of digits, or if this amount is fixed).

**Comment by albinahlback** [comment]
Ping @fredrik-johansson @vneiger

**Comment by edgarcosta** [comment]
I disagree with the prefixes for matrix/vector display, i.e., the `{len = LEN; ` or `{r = ROWS, c = COLS; `.
I'm not sure what does that add.

**Comment by albinahlback** [comment]
> I disagree with the prefixes for matrix/vector display, i.e., the `{len = LEN; ` or `{r = ROWS, c = COLS; `. I'm not sure what does that add.

Not really anything. Just prettier IMO than the current way of printing, that is,
```
LEN  x_{1} ... x_{LEN}
    ^-- Doesn't really visually separate the length of the vector from the entries
```

**Comment by edgarcosta** [comment]
My ultimate goal would make copying and pasting into a CAS easier.
so `[x_1, ..., x_{LEN}]` it is a bit more appealable than `{len = LEN; [x_{1}, ..., x_{LEN}]}`

(and at a later stage to read from CAS into FLINT)

**Comment by albinahlback** [comment]
> My ultimate goal would make copying and pasting into a CAS easier. so `[x_1, ..., x_{LEN}]` it is a bit more appealable than `{len = LEN; [x_{1}, ..., x_{LEN}]}`
> 
> (and at a later stage to read from CAS into FLINT)

Sounds reasonable! I will just omit the length parameter then. Thanks for your opinion!

**Comment by fredrik-johansson** [comment]
> Before thinking of merging, we should establish the printing format for all the types.

There is a lot to say about this which may be too much to work into a single pull request.

For vectors, the advantage of ``len  x1 x2 x3`` is just that it is easy to parse, and it is what ``fmpz_poly_set_str`` et al. currently support. But if we are redesigning things for ``flint_printf`` then I think ``[x1, x2, x3]`` is a good default for vectors.

BTW, it would make sense to unify the ``flint_printf`` backend code with ``calcium_stream_t`` / ``gr_stream_t``, in particular to allow printing to strings as well as files without duplicate implementations.

**Comment by albinahlback** [comment]
> > Before thinking of merging, we should establish the printing format for all the types.
> 
> There is a lot to say about this which may be too much to work into a single pull request.
> 
> For vectors, the advantage of `len x1 x2 x3` is just that it is easy to parse, and it is what `fmpz_poly_set_str` et al. currently support. But if we are redesigning things for `flint_printf` then I think `[x1, x2, x3]` is a good default for vectors.

Thanks for your input!

> BTW, it would make sense to unify the `flint_printf` backend code with `calcium_stream_t` / `gr_stream_t`, in particular to allow printing to strings as well as files without duplicate implementations.

Sounds great!

**Comment by edgarcosta** [comment]
> For vectors, the advantage of `len x1 x2 x3` is just that it is easy to parse, and it is what `fmpz_poly_set_str` et al. currently support. But if we are redesigning things for `flint_printf` then I think `[x1, x2, x3]` is a good default for vectors.

This makes it easier for the coder, but not easier for the user.

**Comment by albinahlback** [comment]
@fredrik-johansson Look at this! It was a lot of work, but I think it is complete. I will just update the documentation as well.

**Comment by albinahlback** [comment]
So, some changes.

This supports printing the base types:
- `nmod_t`
- `fmpz_t`
- `fmpz_mod_ctx_t`
- `fmpq_t`
- `mag_t`
- `arf_t`
- `arb_t`
- `acb_t`

Here, `nmod_t` is printed as `mod MOD`, and likewise for `fmpz_mod_ctx_t`.

`fmpz_t` is printed as usual.

`fmpq_t` is now printed as `NUM` or `NUM / DEN` (note the spaces between `/`), where the former is printed if it is an integer.

`mag_t` and `arf_t` are printed through `arf_get_str` with the exception if they represent a zero. For zeros, I want to emphasize to the user that the zero may not be exact. Hence, I chose to print zeros as `0.00000`.

For `arb_t`, we print through `arb_get_str` **unless* it represents an integer. If it is an integer we print it as an `fmpz_t`.

For `acb_t`, we print it like `arb_t`, but also with special cases, so we can print stuff like `3 - i`, `3 + i`, `3 + 2 * i`, `3 - 2 * i`. We also omit printing the real or imaginary part if they are zero. If the complex number is zero exactly, then we print `0`.

**Comment by albinahlback** [comment]
For composite types (vectors, matrices and polynomials):

- Vectors are printed like `[x_{1}, ..., x_{N}]`.
- Matrices are printed like `[*first row vector*, ..., *N'th row vector*]` were row vectors are printed through the vector printing method.
- Polynomials are printed like `-x^3 + 10 * x - 34` (there are a few cases here, I won't iterate them all, but I think they are very pretty when printed ;-))

**Comment by albinahlback** [comment]
Okay, looks like only GLIBC with GCC on Linux liked my code. Will try to fix this.

**Comment by albinahlback** [comment]
For Clang, it seems like you really need to specify the vector lengths one pushes into `flint_printf` as `slong`s. Will make sure to document this. Anyway, Clang should work now at least.

**Comment by albinahlback** [comment]
Fixed some warnings for Clang while I was at it.

**Comment by albinahlback** [comment]
Looks like `src/test/main` was not tested in CMake. I am trying to fix that as well.

**Comment by albinahlback** [comment]
Please leave feedback!

**Comment by albinahlback** [comment]
It should finally work on all systems (apparently MinGW defines `wint_t` as `unsigned short int`).

**Comment by albinahlback** [comment]
We should probably extend this printing functionality in the future, but it should be backwards-compatible. I will merge tomorrow if there are no objections.

**Comment by fredrik-johansson** [comment]
Some comments:

* I wonder if ``%{type_vec}`` should be either ``%{_type_vec}`` or ``%{type*}``, in the event that we actually add ``fmpz_vec_t`` and friends in the future (there is already a ``gr_vec_t``).
* Printing ``fmpq``:s with spaces seems undesirable in general. I also don't think there should be spaces around ``*`` when printing polynomials.
* Already a bug in ``fmpz_fprintf``: we shouldn't be using ``mpz_out_str`` but rather our own string conversion code (``fmpz_get_str``).
* Instead of reimplementing generic printing for polynomials, vectors and matrices here, it should be possible to reuse the ``gr`` functions. Does something in the ``gr`` code need to be fixed before doing so?
* Printing integer-valued ``arb``:s as integers isn't safe as the values could be large. In general, at least to begin with, it would be better to just call the existing printing functions with minimal customizations.

**Comment by albinahlback** [comment]
> * I wonder if `%{type_vec}` should be either `%{_type_vec}` or `%{type*}`, in the event that we actually add `fmpz_vec_t` and friends in the future (there is already a `gr_vec_t`).

Yes, good idea.

> * Printing `fmpq`:s with spaces seems undesirable in general.

Typographically, no. The slash operator is an operator and should be surrounded by smaller spaces. I would argue that `1/3` has too little of space as compared to `1 / 3` having too big of space.

> I also don't think there should be spaces around `*` when printing polynomials.

Hmm, I really do not agree here. The multiplication operator should be surrounded by space. If we were to write it using `·` instead of `*`, I would agree, but `*` has too little space on most fonts.

> * Already a bug in `fmpz_fprintf`: we shouldn't be using `mpz_out_str` but rather our own string conversion code (`fmpz_get_str`).

Good catch!

> * Printing integer-valued `arb`:s as integers isn't safe as the values could be large. In general, at least to begin with, it would be better to just call the existing printing functions with minimal customizations.

That's true. However, I really want to signify to the user that `arb` are real numbers. For integers with less than `DIGITS + SOME_NUMBER` digits, we could print the integer, but then for bigger numbers we could print `MANTISSA * 2^{EXP_BITS}`?

**Comment by albinahlback** [comment]
> * Instead of reimplementing generic printing for polynomials, vectors and matrices here, it should be possible to reuse the `gr` functions. Does something in the `gr` code need to be fixed before doing so?

Yes! First, compact printing of matrices. Second, we would need the printing methods to return the number of characters written.

**Comment by albinahlback** [comment]
Just as a side-note: I think we can make the printing function faster by utilizing `switch` statements instead of a lot of `if` statements, but that would make it less readable than what it is now.

**Comment by albinahlback** [comment]
I also added a simple check for `flint_printf`, but not all systems seems to like my way of redirecting `stdout`, so currently it is only available if coverage is enabled and `unistd.h` exists.

**Pull request merged**
