### PR TITLE
Add check for BLAS with OpenMP

### PR DESCRIPTION
**Pull request by albinahlback**

### CODE REVIEW

**Comment by thofma** [comment]
With aed3b81285c8181a863c53e7c3a9938c663e4bc1 from your repo I get the same error: [config.log](https://gist.github.com/thofma/16a91abacc1fbdb3a7bdbe6816a6457c). Seems like the flag was not picked up?

**Comment by albinahlback** [comment]
You suppose you have to specify `-fopenmp` somewhere when compiling FLINT. Do you push this to some option (like CFLAGS)? If so, which one?

**Comment by thofma** [comment]
I now pushed it to `CFLAGS` and still get
```
configure:17263: checking for cblas_dgemm in -lopenblas
configure:17286: cc -std=gnu11 -o conftest -fopenmp  -I/workspace/destdir/include -I/workspace/destdir/include -I/workspace/destdir/include  -L/workspace/destdir/lib -L/workspace/destdir/lib -L/workspace/destdir/lib conftest.c -lopenblas  -pthread -lmpfr -lgmp -lm  >&5
/workspace/destdir/lib/libopenblas.so: undefined reference to `GOMP_parallel@GOMP_4.0'
collect2: error: ld returned 1 exit status
```

**Comment by thofma** [comment]
```
sandbox:${WORKSPACE}/srcdir/flint2 # readelf -d ${prefix}/lib/libopenblas.so

Dynamic section at offset 0xddaf80 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgfortran.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libgomp.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libopenblas.so]
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN]
 0x000000000000000c (INIT)               0x76110
 0x000000000000000d (FINI)               0xdad690
 0x0000000000000004 (HASH)               0xe16428
 0x0000000000000005 (STRTAB)             0xe00000
 0x0000000000000006 (SYMTAB)             0xabf8
 0x000000000000000a (STRSZ)              91174 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0xdebd28
 0x0000000000000002 (PLTRELSZ)           100560 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x5d818
 0x0000000070000000 (PPC64_GLINK)        0xda94f8
 0x0000000070000003 (PPC64_OPT)          0x0
 0x0000000000000007 (RELA)               0x4c580
 0x0000000000000008 (RELASZ)             70296 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffb (FLAGS_1)            Flags: ORIGIN
 0x000000006ffffffe (VERNEED)            0x4c4a0
 0x000000006fffffff (VERNEEDNUM)         6
 0x000000006ffffff0 (VERSYM)             0x48f58
 0x000000006ffffff9 (RELACOUNT)          6
 0x0000000000000000 (NULL)               0x0
```

**Comment by albinahlback** [comment]
Looks like it caches the previous checks as it doesn't include `-fopenmp` in the compiler options. I want to avoid including `-fopenmp`, so I think I have to do a manual check with `AC_LINK_IFELSE`.

**Comment by thofma** [comment]
Hm, I see an `cc -std=gnu11 -o conftest -fopenmp [...]` which should be OK? Or I am misunderstanding something?

**Pull request closed without merging**
