### PR TITLE
Inline `fmpz_abs` and `fmpz_neg` with `__builtin_constant_p`

### PR DESCRIPTION
**Pull request by albinahlback**

### CODE REVIEW

**Comment by albinahlback** [comment]
I would like to `fmpz_abs` to expand into two different expressions depending on `__builtin_constant_p(f1 == f2) && f1 == f2`. If this is the case, inline the simpler function. If not, call the default function. But I think that would require us to let `fmpz_abs` to have a different symbol (such as `_fmpz_abs`).

**Comment by fredrik-johansson** [comment]
> But I think that would require us to let fmpz_abs to have a different symbol (such as _fmpz_abs).

That would make sense. Alternatively, we could have a single-argument ``fmpz_neg_inplace`` and ``fmpz_abs_inplace``... though I'm not really a fan of that solution.

**Comment by albinahlback** [comment]
What we could do is actually change the symbol to `_FUNCTION` for all such functions (like `_arf_neg`, `_fmpz_abs`, etc.), gather them into a single commit (hence one single version number).

**Comment by albinahlback** [comment]
> > But I think that would require us to let fmpz_abs to have a different symbol (such as _fmpz_abs).
> 
> That would make sense. Alternatively, we could have a single-argument `fmpz_neg_inplace` and `fmpz_abs_inplace`... though I'm not really a fan of that solution.

Okay, I think I am actually more in favor of your solution in terms of conformity.

Say we implement `fmpz_abs` with builtin_constant_p. Then we could do the same with `fmpz_mul(z, x, x)` -> `fmpz_sqr(z, x)` and `fmpz_add(z, x, x)` -> `fmpz_mul_2exp(z, x, 1)`. But then we have so much to implement, and in the end I think we have to let the user be smart and have smart approaches with good functions. IMO our job is to have a good library, not smart solutions for naive approaches.

**Comment by fredrik-johansson** [comment]
Yes, it's a good point that lots of operators have this potential special-casing.

Another example is ``fmpz_add_ui(x, x, 1)`` which could be something like ``fmpz_increment(x)`` instead.

**Pull request closed without merging**
