### PR TITLE
Disable debug information for runners

### PR DESCRIPTION
**Pull request by albinahlback**
Unless `--enable-coverage`. Opinions, @fredrik-johansson? We do know that `--enable-debug` enlarges the binaries by quite a bit.

### CODE REVIEW

**Comment by albinahlback** [comment]
I know that it has been said before that `-g` should be the default, but I don't really see why. It increases size, reduces performance and libraries like GMP does not have that as a default flag.

**Comment by fredrik-johansson** [comment]
I'd like to hear input from others.

The size and compile time reductions are significant, but it's very useful to have precise debug info when users (frequently) manage to crash FLINT.

**Comment by thofma** [comment]
FWIW, I vote for keeping it.

**Comment by edgarcosta** [comment]
For our own CI, I'm okay with disabling the debug option, but I would not do that by default.

> reduces performance

this is unclear to me

**Comment by albinahlback** [comment]
> > reduces performance
> 
> this is unclear to me

Perhaps not true, but it was a good argument! ;)

**Comment by albinahlback** [comment]
Yeah, looks like I lost this fight haha

**Pull request merged**
