### PR TITLE
Reduce more headers

### PR DESCRIPTION
**Pull request by albinahlback**
* Remove `string.h` inclusion from `mpoly.h` by making `mpoly_copy_monomials`, but still providing a symbol.
* Remove some unnecessary `ulong_extras.h` inclusions.
* Cleanup `fmpz_vec.h`.
* Merge the trigonometric series source files in `nmod_poly`.
* Write a proper function for `fmpz_mul2_uiui` and deinline `fmpz_divexact2_uiui` (with a slight modification for GNU compilers).
* Remove `longlong.h` inclusion from `fmpz.h`.
* Simplify `MAG_FIXMUL` for 32-bit systems, so one can remove `longlong.h` inclusion there completely.
* Reduce `arb_mat.h` and `acb_mat.h` via deinlining and removing, now, redundant headers.
* Convert `n_[cf]log(X, 2)` to `FLINT_[CF]LOG2(X)`
* Remove `acb.h` inclusion from `acb_dirichlet.h`

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
It's annoying to have to include specific system headers before header files to use standard functions, e.g. ``<string.h>`` before ``<mpoly.h>`` for ``mpoly_copy_monomials``. We might as well deinline, or replace ``memcpy`` with a loop.

**Comment by albinahlback** [comment]
> It's annoying to have to include specific system headers before header files to use standard functions, e.g. `<string.h>` before `<mpoly.h>` for `mpoly_copy_monomials`. We might as well deinline, or replace `memcpy` with a loop.

How about something like
```c
#if BUILDING_FLINT
# define mpoly_copy_monomials(bla...) ...
#else
/* Declare symbol */
#endif
```
So that it actually evaluate to `memcpy` when building the library?

**Comment by fredrik-johansson** [comment]
-1 to ``BUILDING_FLINT``.

If the ``string.h`` inclusion is a problem, not inlining this function seems like the easiest solution.

**Comment by albinahlback** [comment]
I think this is the best solution. If the compiler is GCC compatible, it will provide `__builtin_memcpy`, and so we simply expand to that. Otherwise, just use the symbol.

**Pull request merged**
