### PR TITLE
Drop MPIR

### PR DESCRIPTION
**Pull request by albinahlback**
Draft on dropping support of MPIR. I think it is time since it is no longer maintained.

### CODE REVIEW

**Comment by albinahlback** [comment]
> Fine with me once you get it working.
> 
> By the way, do we actually still support GMP 5.1.1 and MPFR 3.0.0 as claimed in the documentation? I think we could well ask that users have 6.3.0 and 4.2.0.

I will set GMP's lowest acceptable version to 6.2.1 in order to make it work for `vcpkg`. I will add tests in `configure.ac` and in `CMakeLists.txt` so that the configuration fails if the version numbers are lower than this. Will update the documentation as well. Thanks for your input.

**Comment by fredrik-johansson** [comment]
BTW, I'd be happier if you squashed the commits here.

**Comment by albinahlback** [comment]
> BTW, I'd be happier if you squashed the commits here.

Yes, I will. I always try to squash the commits before merging! :-)

**Comment by albinahlback** [comment]
I found the error for the fail. Apart from that I want to cache vcpkg so that we do not waste 20 minutes on building GMP and MPFR for every push.

**Comment by albinahlback** [comment]
Looking good som dem säger i Amerika! When everything passes, I will squash one or two commits and merge.

**Pull request merged**
