### PR TITLE
Cleanup headers

### PR DESCRIPTION
**Pull request by albinahlback**
Went through all the headers in `BUILD_DIRS` in the Makefile from `thread_pool` to `qfb` (so FLINT "proper" + Antic, that is, not Arb, Calcium or GR).

Reduced multiline declarations of functions to oneliners and gather them nicely. Also, if an inlined function only contained one to three very simple lines (such that you could guess the code based on its name), I reduced the definition to a one liner, such as
```c
FMPZ_POLY_INLINE slong fmpz_poly_length(const fmpz_poly_t poly) { return poly->length; }
```

I did this because because of the following argument. When you look at headers, you typically look through a lot of functions and try to sort out what you are looking for (or perhaps what is missing). You tend to also look for the list of arguments that a function takes in, but that you tend to find in the documentation as well along with a description of the function. Moreover, having the arguments on the function on multiple lines typically look like this:
```c
void nmod_mpoly_to_mpolyun_perm_deflate_threaded_pool(
                nmod_mpolyun_t A, const nmod_mpoly_ctx_t uctx,
                const nmod_mpoly_t B, const nmod_mpoly_ctx_t ctx,
                const slong * perm, const ulong * shift, const ulong * stride,
                        const thread_pool_handle * handles, slong num_handles);
```
which, in my opinion, makes this specific function *a little bit* more readable, while making the whole header file *much less* readable. I should also add that I don't wrap the lines in my editor, which might make it more readable for me, while making it less readable for others who don't. This should be in line of what happens in `gr.h` for example.

Also, this reduces the size of the headers (in terms of bytes per header).

I removed a couple of unnecessary inclusions in the headers as well, so I think all headers I went through have been pruned of inclusions by almost as good as it gets. In total, I saw a reduction in compile time with 2.2%, which isn't that much, but it is something.

Also removed the deprecation notices in forms of macros. This includes all the `*_mp[z/q]` functions that where deprecated before, but also `invert_limb` in `ulong_extras.h`. They have all been deprecated for at least half a year, so I think it is time to remove them.

I also removed one function `_long_vec_print` as it is never used within the repo.

Also removed the version numbers from Calcium, Arb and Antic. (This solves #1560)

Also silenced some compiler warnings for GCC 13.2.1. (This solves #1608)

Also introduces `fmpq_extras.h`. (This solves #1596)

### CODE REVIEW

**Comment by albinahlback** [comment]
The commits should be nicely separated, so if someone is unhappy with any of them, I can easily change or revert them.

**Comment by fredrik-johansson** [comment]
Not a fan of putting inline functions on a single line when they clearly exceed 80 characters, e.g. don't do this:

    FMPZI_INLINE void fmpzi_add(fmpzi_t res, const fmpzi_t x, const fmpzi_t y) { fmpz_add(fmpzi_realref(res), fmpzi_realref(x), fmpzi_realref(y)); fmpz_add(fmpzi_imagref(res), fmpzi_imagref(x), fmpzi_imagref(y)); }

``gr.h`` is not a good style guide for the rest of FLINT.

**Comment by fredrik-johansson** [comment]
> In my opinion, I think the example you gave it should look like:

I agree, this is the nicest way to format function declarations with very long parameter lists.

**Comment by albinahlback** [comment]
Okay, I will try to fix this then. I just want to say that I find the header more readable when written like this:
```c
void fmpz_mod_poly_factor_equal_deg_with_frob(fmpz_mod_poly_factor_t factors, const fmpz_mod_poly_t f, slong d, const fmpz_mod_poly_t frob, const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_equal_deg(fmpz_mod_poly_factor_t factors, const fmpz_mod_poly_t pol, slong d, const fmpz_mod_ctx_t ctx);

void fmpz_mod_poly_factor_distinct_deg_with_frob(fmpz_mod_poly_factor_t res, const fmpz_mod_poly_t poly, const fmpz_mod_poly_t polyinv, const fmpz_mod_poly_t frob, const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_distinct_deg(fmpz_mod_poly_factor_t res, const fmpz_mod_poly_t poly, slong * const * degs, const fmpz_mod_ctx_t ctx);

void fmpz_mod_poly_factor_distinct_deg_threaded_with_frob(fmpz_mod_poly_factor_t res, const fmpz_mod_poly_t poly, const fmpz_mod_poly_t polyinv, const fmpz_mod_poly_t frob, const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_distinct_deg_threaded(fmpz_mod_poly_factor_t res, const fmpz_mod_poly_t poly, slong * const * degs, const fmpz_mod_ctx_t ctx);

void fmpz_mod_poly_factor_berlekamp(fmpz_mod_poly_factor_t factors, const fmpz_mod_poly_t f, const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_cantor_zassenhaus(fmpz_mod_poly_factor_t res, const fmpz_mod_poly_t f, const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_kaltofen_shoup(fmpz_mod_poly_factor_t res, const fmpz_mod_poly_t poly, const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_squarefree(fmpz_mod_poly_factor_t res, const fmpz_mod_poly_t f, const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor(fmpz_mod_poly_factor_t res, const fmpz_mod_poly_t f, const fmpz_mod_ctx_t ctx);

```
as compared to this:
```c
void fmpz_mod_poly_factor_equal_deg_with_frob(
        fmpz_mod_poly_factor_t factors,
        const fmpz_mod_poly_t f,
        slong d,
        const fmpz_mod_poly_t frob,
        const
        fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_equal_deg(
        fmpz_mod_poly_factor_t factors,
        const fmpz_mod_poly_t pol,
        slong d,
        const fmpz_mod_ctx_t ctx);

void fmpz_mod_poly_factor_distinct_deg_with_frob(
        fmpz_mod_poly_factor_t res,
        const fmpz_mod_poly_t poly,
        const fmpz_mod_poly_t polyinv,
        const fmpz_mod_poly_t frob,
        const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_distinct_deg(
        fmpz_mod_poly_factor_t res,
        const fmpz_mod_poly_t poly,
        slong * const * degs,
        const fmpz_mod_ctx_t ctx);

void fmpz_mod_poly_factor_distinct_deg_threaded_with_frob(
        fmpz_mod_poly_factor_t res,
        const fmpz_mod_poly_t poly,
        const fmpz_mod_poly_t polyinv,
        const fmpz_mod_poly_t frob,
        const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_distinct_deg_threaded(
        fmpz_mod_poly_factor_t res,
        const fmpz_mod_poly_t poly,
        slong * const * degs,
        const fmpz_mod_ctx_t ctx);

void fmpz_mod_poly_factor_berlekamp(
        fmpz_mod_poly_factor_t factors,
        const fmpz_mod_poly_t f,
        const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_cantor_zassenhaus(
        fmpz_mod_poly_factor_t res,
        const fmpz_mod_poly_t f,
        const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_kaltofen_shoup(
        fmpz_mod_poly_factor_t res,
        const fmpz_mod_poly_t poly,
        const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor_squarefree(
        fmpz_mod_poly_factor_t res,
        const fmpz_mod_poly_t f,
        const fmpz_mod_ctx_t ctx);
void fmpz_mod_poly_factor(
        fmpz_mod_poly_factor_t res,
        const fmpz_mod_poly_t f,
        const fmpz_mod_ctx_t ctx);
```
because I can get a better overview of all the functions. But, I will make a fix for this then.

**Comment by fredrik-johansson** [comment]
Probably in that case, yeah. There isn't going to be a single style that gives optimal results everywhere.

Incidentally we do have an ``indent`` command in ``code_conventions.txt`` that is supposed to define our indent style, but it's not being followed (and I think it messes up header files).

**Comment by albinahlback** [comment]
I used the following script to do this commit:
```bash
files="thread_pool.h thread_support.h ulong_extras.h long_extras.h perm.h double_extras.h d_vec.h d_mat.h mpn_extras.h mpf_vec.h mpf_mat.h mpfr_vec.h mpfr_mat.h nmod.h nmod_vec.h nmod_mat.h nmod_poly.h fmpz.h fmpz_vec.h fmpz_mat.h fmpz_poly.h fmpz_mod.h fmpz_mod_vec.h fmpz_mod_mat.h fmpz_mod_poly.h fmpq.h fmpq_vec.h fmpq_mat.h fmpq_poly.h fq.h fq_vec.h fq_mat.h fq_poly.h fq_nmod.h fq_nmod_vec.h fq_nmod_mat.h fq_nmod_poly.h fq_zech.h fq_zech_mat.h fq_zech_poly.h fq_default.h fq_default_mat.h fq_default_poly.h fq_embed.h fq_nmod_embed.h fq_zech_embed.h padic.h padic_mat.h padic_poly.h qadic.h nmod_poly_factor.h fmpz_factor.h fmpz_poly_factor.h fmpz_mod_poly_factor.h fq_poly_factor.h fq_nmod_poly_factor.h fq_zech_poly_factor.h fq_default_poly_factor.h nmod_poly_mat.h fmpz_poly_mat.h mpoly.h nmod_mpoly.h fmpz_mpoly.h fmpz_mod_mpoly.h fmpq_mpoly.h fq_nmod_mpoly.h fq_zech_mpoly.h nmod_mpoly_factor.h fmpz_mpoly_factor.h fmpz_mod_mpoly_factor.h fmpq_mpoly_factor.h fq_nmod_mpoly_factor.h fq_zech_mpoly_factor.h fft.h fft_small.h fmpz_poly_q.h fmpz_lll.h n_poly.h arith.h qsieve.h aprcl.h nf.h nf_elem.h qfb.h"

for file in ${files};
do
    # Do inline functions, they cannot be greater than 85 in line width
    perl -i -pe 's/(\w+_INLINE) (.*) { (.*) }/\1\n\2\n{\n    \3\n}/ if length($_) > 85' $file

    # Do function declarations, they cannot be greater than 90 in line width
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\n    ${6}\n    ${7}\n    ${8}\n    ${9}\n    ${10}\n    ${11}\n    ${12}\n    ${13}\n    ${14}\n    ${15}\n    ${16}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\n    ${6}\n    ${7}\n    ${8}\n    ${9}\n    ${10}\n    ${11}\n    ${12}\n    ${13}\n    ${14}\n    ${15}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\n    ${6}\n    ${7}\n    ${8}\n    ${9}\n    ${10}\n    ${11}\n    ${12}\n    ${13}\n    ${14}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\n    ${6}\n    ${7}\n    ${8}\n    ${9}\n    ${10}\n    ${11}\n    ${12}\n    ${13}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\n    ${6}\n    ${7}\n    ${8}\n    ${9}\n    ${10}\n    ${11}\n    ${12}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\n    ${6}\n    ${7}\n    ${8}\n    ${9}\n    ${10}\n    ${11}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\n    ${6}\n    ${7}\n    ${8}\n    ${9}\n    ${10}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\n    ${6}\n    ${7}\n    ${8}\n    ${9}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\n    ${6}\n    ${7}\n    ${8}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\n    ${6}\n    ${7}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\n    ${6}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\n    ${5}\);/ if length($_) > 90' $file
    perl -i -pe 's/(\w+[ \*]+[\w0-9]+)\( *(.*,) *(.*,) *(.*)\);/${1}\(\n    ${2}\n    ${3}\n    ${4}\);/ if length($_) > 90' $file
    # If they have less than 4 arguments, it should be easy to read
done
```

**Comment by albinahlback** [comment]
If this isn't good enough, I will close this PR. (Not saying this with any tone.)

**Comment by fredrik-johansson** [comment]
Well, seeing what it looks like I think I've changed my mind and prefer the single-line prototypes :-) The long one-line inline functions are not so pretty though.

Most of the cleanup in this PR *apart* from reformatting the header files seems fine though. Could you make a PR with just those changes so that we can separate the concerns?

**Pull request closed without merging**
