### PR TITLE
Improve accuracy of nfloat subtraction and hardcode add/sub up to nlimbs=4

### PR DESCRIPTION
**Pull request by fredrik-johansson**
New timings (edit: updated with new dot product results):

```
                   _gr_vec_add          _gr_vec_mul          _gr_vec_mul_scalar   _gr_vec_sum          _gr_vec_product      _gr_vec_dot
prec = 64
n =   10        3.330e-08 (3.904x)   1.780e-08 (7.303x)   1.440e-08 (9.167x)   4.630e-08 (2.441x)   3.320e-08 (3.494x)   2.450e-08 (1.992x)
n =  100        3.070e-07 (4.137x)   1.450e-07 (9.172x)   1.120e-07 (11.964x)   4.580e-07 (2.860x)   4.120e-07 (3.374x)   1.830e-07 (2.038x)
prec = 128
n =   10        4.220e-08 (4.882x)   2.670e-08 (5.393x)   2.530e-08 (5.810x)   4.960e-08 (3.548x)   4.190e-08 (3.079x)   3.830e-08 (1.705x)
n =  100        3.890e-07 (5.270x)   2.430e-07 (5.926x)   2.200e-07 (6.636x)   6.030e-07 (3.483x)   5.370e-07 (2.793x)   3.120e-07 (1.622x)
prec = 192
n =   10        5.240e-08 (4.542x)   5.810e-08 (2.857x)   5.690e-08 (2.970x)   5.810e-08 (3.649x)   5.650e-08 (2.673x)   7.500e-08 (2.387x)
n =  100        4.930e-07 (4.929x)   5.650e-07 (3.044x)   5.550e-07 (3.153x)   5.850e-07 (4.308x)   7.030e-07 (2.589x)   6.750e-07 (2.459x)
prec = 256
n =   10        6.250e-08 (4.048x)   7.620e-08 (2.454x)   7.390e-08 (2.530x)   5.910e-08 (3.672x)   7.330e-08 (2.292x)   9.920e-08 (2.056x)
n =  100        5.690e-07 (4.429x)   7.450e-07 (2.523x)   7.260e-07 (2.617x)   6.530e-07 (4.012x)   8.910e-07 (2.290x)   9.230e-07 (2.080x)
prec = 512
n =   10        1.320e-07 (2.045x)   1.630e-07 (1.988x)   1.610e-07 (2.006x)   9.840e-08 (2.358x)   1.460e-07 (1.979x)   2.510e-07 (1.422x)
n =  100        1.290e-06 (2.116x)   1.640e-06 (2.030x)   1.620e-06 (2.105x)   1.120e-06 (2.563x)   1.680e-06 (2.077x)   2.390e-06 (1.494x)
prec = 1024
n =   10        1.760e-07 (1.801x)   7.550e-07 (1.325x)   7.530e-07 (1.320x)   1.260e-07 (2.048x)   7.180e-07 (1.231x)   8.260e-07 (1.271x)
n =  100        1.740e-06 (1.799x)   7.830e-06 (1.341x)   7.810e-06 (1.408x)   1.510e-06 (2.199x)   8.310e-06 (1.324x)   8.260e-06 (1.320x)
prec = 2048
n =   10        2.370e-07 (1.688x)   2.440e-06 (1.279x)   2.450e-06 (1.273x)   1.800e-07 (1.817x)   2.260e-06 (1.235x)   2.560e-06 (1.121x)
n =  100        2.450e-06 (1.620x)   2.500e-05 (1.356x)   2.490e-05 (1.434x)   2.120e-06 (1.929x)   2.520e-05 (1.389x)   2.550e-05 (1.149x)
```

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
> Wow, that's huge! Perhaps we should fix `mpn_addlshC` for fixed sizes as well? I will fix the assembly some day.

Fused shift+add/sub would definitely be useful.

**Comment by fredrik-johansson** [comment]
I will need to try to find some real-world benchmarks soon. The problem with the hardcoded addition/subtraction code right now is that it is extremely branchy. That means it's potentially much slower than suggested for workloads where unfavorable branch prediction patterns.

**Comment by albinahlback** [comment]
In what way? Would functions (i.e. functions with symbols) in a table work (just like we have with the hardcoded multiplication functions)?

**Comment by fredrik-johansson** [comment]
> In what way? Would functions (i.e. functions with symbols) in a table work (just like we have with the hardcoded multiplication functions)?

Combined shift-add/sub functions would help in the generic case by being faster than a separate ``mpn_rshift`` and ``mpn_add_n``/``mpn_sub_n``, and I guess having various hardcoded cases here would be faster too.

About replacing branches in the nfloat addition with more function table lookups, maybe... but it's a bit tricky. You'd presumably want to dispatch based on the sign, the number of limbs to shift, and whether the number of bits to shift inside a limb is zero. You'd need some fiddling to put all those conditions in a single table, and that's not necessarily faster than some branches (at least when they are predictable).

**Comment by albinahlback** [comment]
Hmm, what about implementing `mpn_(add|sub)(l|r)sh`-type hardcoded routines which, inside these routines, follows up the chain with a `MPN_(INC|DEC)R_U`? In this way, we can check which input is the largest, then "shift the limbs" in appropriate operand before calling this routine, and it will take care of everything after that. No need to know the size of the biggest operand, just the smallest. That would need a comparison before calling, but that is usually very fast. A normalization could be implemented as well inside these routines, although that is very unlikely to happen.

**Pull request merged**
