### PR TITLE
Draft on 32-bit CI

### PR DESCRIPTION
**Pull request by albinahlback**

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Hope this works!

I think it would be prudent to enable asserts for the 32-bit tests.

**Comment by albinahlback** [comment]
> Hope this works!
> 
> I think it would be prudent to enable asserts for the 32-bit tests.

Sounds like a good idea!

**Comment by edgarcosta** [comment]
@tornaria do tests pass on your 32bit machine?

**Comment by albinahlback** [comment]
Looks like `fmpz_set_str` is the problem.

**Comment by albinahlback** [comment]
Could it be that `DIGITS_PER_LIMB` should be 10 for 32-bit `fmpz_set_str`, @fredrik-johansson?

**Comment by tornaria** [comment]
> @tornaria do tests pass on your 32bit machine?

Everything passes here:

https://github.com/void-linux/void-packages/actions/runs/6700948977/job/18207675113?pr=46832

I'm using released 3.0 + #1545 + #1546.

**Comment by tornaria** [comment]
Also, btw, the job I posted builds and checks eclib, singular, and sagemath with the new flintlib.

**Comment by fredrik-johansson** [comment]
> Could it be that `DIGITS_PER_LIMB` should be 10 for 32-bit `fmpz_set_str`, @fredrik-johansson?

It should be 9, but

```
    tmp = TMP_ALLOC(sizeof(mp_limb_t) * (slen / DIGITS_PER_LIMB) + 2);
```

looks like it should be

```
    tmp = TMP_ALLOC(sizeof(mp_limb_t) * (slen / DIGITS_PER_LIMB + 2));
```

**Comment by tornaria** [comment]
I'm now testing 4b27c91aa4597ea7b7751acc0cf03224b6894fcd on i686 (glibc). However, if this is an issue with allocation maybe it's triggered in musl libc and not in glibc.

**Comment by fredrik-johansson** [comment]
It's possible that the bug only manifests itself with ``--enable-assert`` which does change the behavior of ``TMP_ALLOC``.

**Comment by tornaria** [comment]
Could also be a bug in gcc since you are getting 13.2 and I'm running 12.2. Is it feasible to test with an earlier version of alpine?

**Comment by tornaria** [comment]
Build and check of 4b27c91aa4597ea7b7751acc0cf03224b6894fcd finished without any failure.

**Comment by fredrik-johansson** [comment]
Trying this on a 32-bit debian in VirtualBox. The ``fmpz_is_prime`` test passes, but valgrind does show a bunch of errors. They go away when fixing the ``TMP_ALLOC`` line mentioned above.

**Comment by tornaria** [comment]
> It's possible that the bug only manifests itself with `--enable-assert` which does change the behavior of `TMP_ALLOC`.

I redid the build + check adding `--enable-assert` to configure, and the test works fine.

**Comment by tornaria** [comment]
> Trying this on a 32-bit debian in VirtualBox. The `fmpz_is_prime` test passes, but valgrind does show a bunch of errors. They go away when fixing the `TMP_ALLOC` line mentioned above.

IME, musl allocator is less forgiving to allocation mistakes, so it's good that you test on alpine.

I do test musl, but only x86_64 since void doesn't do i686-musl binaries (I'd have to rebuild the whole system).

While running the whole testsuite on `--enable-assert` I got:
```
ecm....t-ecm: src/ulong_extras/mulmod_preinv.c:22: n_mulmod_preinv: Assertion `a < n' failed.
```

**Comment by fredrik-johansson** [comment]
The allocation bug is fixed in 6c92f365a35202ceb972171cf9a0355f3eec1f3a.

**Comment by albinahlback** [comment]
I will increase the test multiplier once it passes all the tests so that it matches in time with Ubuntu GCC AVX2 x10, so that we may detect more bugs.

**Comment by albinahlback** [comment]
Test fails for `fmpz_factor_ecm`

**Comment by fredrik-johansson** [comment]
The ECM bug may be fixed in 016de13. Tests now pass for me on 32-bit.

Note to self: the ECM code needs a thorough review.

**Comment by fredrik-johansson** [comment]
Nice!

**Pull request merged**
