### PR TITLE
Enable fft_small module for CMake builds

### PR DESCRIPTION
**Pull request by albinahlback**
I made the fft_small module available for MSVC systems that supports AVX2 or ARM NEON instructions.

Also changed definitions of `FLINT_NORETURN` and `FLINT_TLS_PREFIX` to the C standards.

I also enabled test checking for the Ubuntu CMake runner.

### CODE REVIEW

**Comment by albinahlback** [comment]
Hopefully this fixes #1629

**Comment by albinahlback** [comment]
Hey, it does work! Summoning @fredrik-johansson!

I messed up with the merge of two different branches, so I never managed to squash the commits properly and the commits are a little bit in the wrong order (for example, "disable fft_small for MSVC" comes after the enabling of it, which is incorrect). Hopefully this is okay though.

**Comment by fredrik-johansson** [comment]
Nothing really objectionable as far as I can tell.

The ``add_sssssaaaaaaaaaa`` etc. fallbacks look like they might not necessarily generate optimal code, so I'd at least like to have an issue open about profiling/improving that.

**Comment by albinahlback** [comment]
> The `add_sssssaaaaaaaaaa` etc. fallbacks look like they might not necessarily generate optimal code, so I'd at least like to have an issue open about profiling/improving that.

Yes. X86 Windows could be using `_addcarry_u64`, but I'm unsure if ARM Windows have any better alternative. But let's open an issue about that instead.

**Pull request merged**
