### PR TITLE
Create unified tests

### PR DESCRIPTION
**Pull request by albinahlback**
*Note: New description*

### Change of code

Currently, all tests in FLINT is basically written in the same way, namely
```c
/* Copyright notice for module/test/t-function.c */

#include "myheaders.h"

int main(void)
{
    mytype_t some_variables;
    FLINT_TEST_INIT(state);

    printf("module_function....");
    fflush(stdout);

    /* PERFORMING TESTS */

    FLINT_TEST_CLEANUP(state);
    printf("PASS\n");
    return 0;
}
```
To streamline this, we can do this instead:
```c
/* Copyright notice for module/test/t-function.c */

#include "test_helpers.h"
#include "myheaders.h"

TEST_FUNCTION_START(module_function, state)
{
    mytype_t some_variables;

    /* PERFORMING TESTS */

    TEST_FUNCTION_END(state);
}
```
with a main function
```c
/* Copyright notice for module/test/main.c */

/* Include system headers */

/* Include functions *********************************************************/

...
#include "t-function.c"
...

/* Array of test functions ***************************************************/

test_struct tests[] =
{
    ...
    TEST_FUNCTION(module_function),
    ...
};

/* main function *************************************************************/

TEST_MAIN(tests)
```

### End result

The end result will be more streamlined tests along with a reduced compile time for the tests as only `module/test/main.c` has to be compiled, in contrast to compiling `module/test/t-*.c` separately. I suspect this will reduce the compile time by at least 50%, but I think one could expect a larger reduction in compile time for the tests.

Also, we should see a great reduction in the number of lines.

### Functionality

In order to only run a subset of test functions, one can do this via `./build/fmpz/test/main fmpz_add fmpz_addmul`, and in this example it will only run the test for `fmpz_add` and `fmpz_addmul`. 

I do not intend to implement multithreaded testing for a single module in this PR, but it would be nice to have this. However, as of now it is not the main priority.

### Bug fixes-ish

As I am going through all files (semi-automatically, just using Vim macros to change everything), I noticed that some functions print the wrong function it tests. All of these are being fixed.

Moreover, some test functions for IO creates a forks in the test functions. As the child processes are never closed, this would lead to multiple processes running the same tests after these IO-tests. Hence, I ensured that these child processes are closed, and that the parent waits until the child process has exited.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
I think you can remove a lot of boilerplate. The macro

    TEST_FUNCTION(acb_acos)

could create a struct entry containing both the function pointer and the string, i.e.

    { test_acb_acos, "acb_acos" }

So you wouldn't need the separate array with

    char acb_acos_name[] = "acb_acos";
    ...

    char * test_names[] =
    ...

**Comment by fredrik-johansson** [comment]
Parallel testing for a single module is quite useful to keep. What are the options?

* Build a test "program" for each function that is just a shell script invoking the main test 
program with its string.
* When the main test program is called without an argument, have it spawn subprocesses instead of calling tests functions in a loop.
* Hack the makefile to accomplish this some other way...?

**Comment by albinahlback** [comment]
> I think you can remove a lot of boilerplate. The macro
> 
> ```
> TEST_FUNCTION(acb_acos)
> ```
> 
> could create a struct entry containing both the function pointer and the string, i.e.
> 
> ```
> { test_acb_acos, "acb_acos" }
> ```
> 
> So you wouldn't need the separate array with
> 
> ```
> char acb_acos_name[] = "acb_acos";
> ...
> 
> char * test_names[] =
> ...
> ```

Thanks for your feedback! Yes, this sounds as the best possible alternative, will do this instead.

**Comment by albinahlback** [comment]
> Parallel testing for a single module is quite useful to keep. What are the options?
> 
>     * Build a test "program" for each function that is just a shell script invoking the main test
>       program with its string.
> 
>     * When the main test program is called without an argument, have it spawn subprocesses instead of calling tests functions in a loop.
> 
>     * Hack the makefile to accomplish this some other way...?

Just so it is out there, I think we can agree that parallell testing within each module when performing all tests throughout FLINT doesn't really matter, and would probably not be beneficial at all.

However, for one module only, I am thinking that a call like
```sh
make check MOD=fmpz [THREAD=1/NTHREADS=8]
```
could invoke threading via
```
./build/fmpz/test/main [THREAD=1/NTHREADS=8]
```
which would spawn threads of whom each works on a subset of tests. Wouldn't be hard to implement. Sounds good?

**Comment by fredrik-johansson** [comment]
We'd have to be careful about running multiple tests in the same process because this changes runtime behaviour: we will enter some tests with cached data (fmpzs, primes, arb constants, thread pool, etc.) whereas tests previously always started with a clean slate. Actually this can be a good thing to test too, but I don't know if it should be the default.

There is a particular problem with using multithreading to run tests in parallel: tests intended specifically to check multithreaded algorithms may end up running serially only because the thread pool is occupied by the competing test programs! (Again, it is also potentially interesting to deliberately test such conditions, but it should maybe not be the default.)

**Comment by fredrik-johansson** [comment]
It looks fine, but I would like to see parallel tests working from the start.

**Comment by albinahlback** [comment]
I think I have an idea of how to check a single module with multiple jobs. Let $N$ denote the number of jobs.

1. In `test_helpers.h`, we modify `TEST_MAIN` so that it can print all possible tests if one puts in some option, say `--print-tests`.
2. In `Makefile`, if $N > 1$ and `MOD` is set, we run a recipe that sets a variable, say `MOD_TESTS`, to all tests for module `MOD`.
3. In `Makefile`, create a partition of `MOD_TESTS` into $N$ variables `MOD_TESTS_1`, ..., `MOD_TESTS_$(N)`.
4. In `Makefile`, we run $N$ recipes that checks module `MOD` with each partition.

The running recipes should look something like
```make
ifdef MOD
define mod_recipe
$(BUILD_DIR)/$(MOD)/test/main_RUN_$(1): $(BUILD_DIR)/$(MOD)/test/main | $(BUILD_DIR)/$(MOD)/test
	@$< $(MOD_TESTS_$(1))
endef

$(foreach job_number, $(JOB_NUMBER_LIST), $(eval $(call mod_recipe,$(job_number))))
endif
```

**Comment by albinahlback** [comment]
@fredrik-johansson Is there a reason why many files contain an empty line at the end of the file?

**Comment by edgarcosta** [comment]
For running the tests in parallel, I would outsource it to the [GNU Parallel](https://www.gnu.org/software/parallel/)

**Comment by albinahlback** [comment]
> For running the tests in parallel, I would outsource it to the [GNU Parallel](https://www.gnu.org/software/parallel/)

I'd prefer if the makefile contains as much code as possible written in native Make, but if I cannot make it work I will consider this. Thanks!

**Comment by edgarcosta** [comment]
In hindsight, I think you are right, native make sounds much more reasonable.

**Comment by fredrik-johansson** [comment]
Another good reason to do this: as mentioned in https://github.com/flintlib/flint/issues/1556, the test executables currently take up a ton of space when building statically.

**Comment by albinahlback** [comment]
Yes, I think I will continue with this as soon as I find time. Probably around the beginning of next week.

As of now it is around 70% done modulo bug fixes. Also have to solve the conflicts.

**Comment by albinahlback** [comment]
Just as a reminder for myself, the work is mainly done through Vim macros and some minor use of `sed`.

There are basically three cases one have to care for: Arb-type tests (no use of `FLINT_INIT_TEST`), FLINT-type tests (use of `FLINT_INIT_TEST`) and template-type tests.

So for a module `mod`, we create the file `mod/test/main.c` by copying a template of it and pushing it into `mod/test/`. Then `ls mod/test/t-*.c >> mod/test/main.c` and finish the file by macros.

Then we start to edit all test files in `mod`. For FLINT-type files, we copy `XXX` in `[flint_]printf("XXX....")` and push that to the first argument in `TEST_FUNCTION_START` with `mod_` prefixed (hence, it will print `mod_function....` instead of `function....` which is very much needed IMO). Then we remove everything line starting from the first line containing `FLINT_TEST_INIT` and ending in the line containing the first `fflush` after `FLINT_TEST_INIT`. In a similar fashion we replace the lines between `FLINT_TEST_CLEANUP` and `return 0` with `TEST_FUNCTION_END`. We also prepend `#include "test_helpers.h"` to the inclusions.

There has been some cases where some `X_init`/`X_clear` has been removed, but these cases has been pretty few. I think I have catched all these cases as I take a quick glance at the beginning and end of the main-function before employing the macros. However, there may have been cases I missed, so it would be nice with a Valgrind run, preferably before merging.

**Comment by fredrik-johansson** [comment]
BTW, what do you think about generating a trivial shell script that invokes the main test program for each test file? This would preserve the ability to browse test programs with tab completion, and I suppose nothing would need to change about the existing ``make -j check``.

**Comment by albinahlback** [comment]
> BTW, what do you think about generating a trivial shell script that invokes the main test program for each test file? This would preserve the ability to browse test programs with tab completion, and I suppose nothing would need to change about the existing `make -j check`.

Could you explain? I'm not sure that I understand

**Comment by fredrik-johansson** [comment]
Currently we build
```
    test/module/t-add
    test/module/t-sub
    test/module/t-mul
```

Instead we would build
```
   test/module/main
   test/module/t-add
   test/module/t-sub
   test/module/t-mul
```

where ``main`` is the actual test executable and ``t-add`` is a one-line shell script that executes ``main add``, etc.

**Comment by albinahlback** [comment]
I do think we want to avoid having to execute multiple executables for each module. I do not see why we would prefer this over something like
```
$ ./build/fmpz/main --num-threads=8 --thread=1
```
where this tests the first partition out of eight.

I would, however, see that the shell executables could be equivalent in the case that we would have fewer files. As we have 3500+ test files, I think the spawning of jobs and the starting of executables takes more time than we  think.

**Comment by albinahlback** [comment]
@fredrik-johansson I think it is done. I would like to avoid further conflicts, so it would be great if we could avoid merging test-related things until this is merged.

I know it is sort of impossible to review every snippet of code, but please ask as many questions as you'd like!

Make sure to try out `make -j [NUM] check MOD=XXX`. Also note that the reduction in compile time for the test is about 89%.

**Comment by fredrik-johansson** [comment]
Cool, I will have a look.

Is the time to *run* the tests affected?

**Comment by fredrik-johansson** [comment]
``make -j check MOD=fmpz`` or ``make -j 8 check MOD=fmpz`` don't seem to be parallel for me. Is there something I need to configure?

**Comment by fredrik-johansson** [comment]
Worth documenting: valgrinding a single test can now be done like

    valgrind build/fmpz/test/main fmpz_divexact

And the traceback (if I introduce a bug) points to the correct line number in the ``t-divexact.c``. Nice!

**Comment by albinahlback** [comment]
> Cool, I will have a look.
> 
> Is the time to _run_ the tests affected?

My calculations show that parallel runs, they have a slightly lower runtime. For single runs, they definitely should have a lower runtime.

> `make -j check MOD=fmpz` or `make -j 8 check MOD=fmpz` don't seem to be parallel for me. Is there something I need to configure?

Hmm, no you shouldn't have to configure anything special. Let me see if I can figure out what's wrong.

**Comment by fredrik-johansson** [comment]
``make -j check`` at least seems to work.

FWIW, here are timings with the old system:

    real        1m10,974s
    user        11m59,166s
    sys         0m17,673s

With the new system:

    real        1m18,814s
    user        10m18,990s
    sys         0m9,576s

So CPU time got a bit better while real time got a bit worse. I wonder why? Perhaps just some of the more long-running, multithreaded tests finishing later.

**Comment by albinahlback** [comment]
> `make -j check MOD=fmpz` or `make -j 8 check MOD=fmpz` don't seem to be parallel for me. Is there something I need to configure?

Can you run
```
make -j print-NJOBS
make -j4 print-NJOBS
make -j print-THREAD_LIST
make -j4 print-THREAD_LIST
```
for me, and write the output here?

**Comment by fredrik-johansson** [comment]
```
make -j print-NJOBS
make -j4 print-NJOBS
make -j print-THREAD_LIST
make -j4 print-THREAD_LIST
NJOBS=
NJOBS=
THREAD_LIST=
THREAD_LIST=
```

If it's relevant,

```
make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
```

**Comment by albinahlback** [comment]
> ```
> make -j print-NJOBS
> make -j4 print-NJOBS
> make -j print-THREAD_LIST
> make -j4 print-THREAD_LIST
> NJOBS=
> NJOBS=
> THREAD_LIST=
> THREAD_LIST=
> ```
> 
> If it's relevant,
> 
> ```
> make --version
> GNU Make 4.3
> Built for x86_64-pc-linux-gnu
> ```

Sorry, edited the comment above. Can you run `make -j print-MAKEFLAGS`?

**Comment by fredrik-johansson** [comment]
```
make -j   print-MAKEFLAGS
make -j 4 print-MAKEFLAGS
MAKEFLAGS= -j
MAKEFLAGS= -j4 --jobserver-auth=3,4
```

**Comment by albinahlback** [comment]
> ```
> make -j   print-MAKEFLAGS
> make -j 4 print-MAKEFLAGS
> MAKEFLAGS= -j
> MAKEFLAGS= -j4 --jobserver-auth=3,4
> ```

Sorry, but I cannot seem to find what is the problem. Can I ask you to run `make -j print-JOBS` and `make -j4 print-JOBS`? The problem should be somewhere between line 94 and 104 in Makefile[.in], but I cannot seem to any faulty logic there...

It works for me, but I have Make 4.4.1.

**Comment by fredrik-johansson** [comment]
```
make -j print-JOBS
JOBS=
make -j4 print-JOBS
JOBS=
```

**Comment by albinahlback** [comment]
But I really want the runtime to be lower before merging. It could signal that something went wrong. For example, in the MSVC runner, `nmod_mat` seems to time out, which is weird.

**Comment by fredrik-johansson** [comment]
OK, parallel ``make -j check MOD=fmpz`` seems to work with make 4.4.

I consider that acceptable as long as ``make -j check`` still works with older versions.

**Comment by albinahlback** [comment]
> OK, parallel `make -j check MOD=fmpz` seems to work with make 4.4.
> 
> I consider that acceptable as long as `make -j check` still works with older versions.

Looks like a lot of work was made on `MAKEFLAGS` in Make 4.4, so I suppose this will only work after 4.3.

**Comment by albinahlback** [comment]
Okay, on Linux with Make 4.4.1, I have performed some tests, and it seems like the tests on this branch indeed is faster when not running in parallel. However, for parallel runs, it is not always the case. The solution seems to be that one runs `make -j$(nproc) check` instead of `make -j check`.

One could alter the flags inside the Makefile, but that requires Make 4.4 I believe.

Will post some benchmarks soon.

**Comment by fredrik-johansson** [comment]
I get the same behavior:

    time make -j9 check
    ...
    real        1m3,334s
    user        8m29,395s
    sys         0m16,298s

Curious; any clue why it's like that?

**Comment by albinahlback** [comment]
> I get the same behavior:
> 
> ```
> time make -j9 check
> ...
> real        1m3,334s
> user        8m29,395s
> sys         0m16,298s
> ```
> 
> Curious; any clue why it's like that?

Nice that you had the same result! I remember seeing something about it on SE, but I don't know the reason behind it.

**Comment by albinahlback** [comment]
Finally. I think it is ready to be merged!

**Comment by fredrik-johansson** [comment]
It looks good. Before merging, I just want to see that test coverage hasn't changed.

Could you update the explanations https://flintlib.org/doc/building.html also? Document the ``make`` version requirements, how to set ``-jN`` correctly, how to test a single module, how to test a single function etc.

**Comment by fredrik-johansson** [comment]
The coverage changes reported by codecov are worth a look. For example, there seem to be functions in ``nmod.h`` and ``fmpz_mpoly_factor.h`` among others that lost coverage. This could just be some issue with the way codecov processes header files though.

**Comment by albinahlback** [comment]
> Could you update the explanations https://flintlib.org/doc/building.html also? Document the `make` version requirements, how to set `-jN` correctly, how to test a single module, how to test a single function etc.

I pushed a commit for this.

**Comment by albinahlback** [comment]
> The coverage changes reported by codecov are worth a look. For example, there seem to be functions in `nmod.h` and `fmpz_mpoly_factor.h` among others that lost coverage. This could just be some issue with the way codecov processes header files though.

Yeah, I really want to fix these things, but looking into it, it seems like there is no change. For example, `fmpz_mpoly_factor_get_exp_si` does not appear once in the trunk (apart from the header file), and not once in this branch. However, codecov now seems to think that it was uncovered...

**Comment by albinahlback** [comment]
Like, there may be a lot of bugs and so on in this PR, but I doubt that this PR will actually decrease the coverage.

**Comment by fredrik-johansson** [comment]
The local coverage report seems to be broken. Doing

```
/configure --enable-coverage --disable-static --enable-avx2
make -j
make -j check
make coverage
```

I get coverage reports for all the test ``main`` programs, not the actual source code.

**Comment by albinahlback** [comment]
> The local coverage report seems to be broken. Doing
> 
> ```
> /configure --enable-coverage --disable-static --enable-avx2
> make -j
> make -j check
> make coverage
> ```
> 
> I get coverage reports for all the test `main` programs, not the actual library source code.

Does my commit work?

**Comment by fredrik-johansson** [comment]
That excludes the tests, but all ``.c`` files in the library are being ignored for some reason (I only get coverage reports for the header files).

**Comment by fredrik-johansson** [comment]
OK, that may just have been something wonky on my end. It works after I changed some search paths.

**Comment by fredrik-johansson** [comment]
OK, will merge this now. Nothing looks obviously wrong, and the CI speedup alone is worth it.

Thanks a lot!

**Pull request merged**
