### PR TITLE
Increase code coverage

### PR DESCRIPTION
**Pull request by albinahlback**
- Sort of breaking change: I renamed `_fmpz_mat_read_only_window_init_strip_initial_zero_rows` to `_fmpz_mat_window_init_readonly_strip_initial_zero_rows`, and renamed and redefined its clearing function to a macro since it does not contain any code (and so it will reduce the size of the FLINT binary a couple of bytes). This will also increase code coverage. These functions are not documented, was implemented a year ago and are only used in `fmpz_lll/is_reduced(_with_removal).c`.
- `ulong_extras/factor_pp1.c` contained code that was only utilized when profiling. Hence, add an option `--enable-profiling` in configuration that enables profiling FLINT, and does activate this piece of code.
- Remove unnecessary branch for `n_cbrt` when `FLINT64`.
- Randomize more tests to increase code coverage.
- Test modulo 1 for `n_sqrtmodn`.
- The documentation states that `n_is_strong_probabprime2_preinv` requires its input `a` to be reduced modulo `n`, but this is not the case in the source code and is not tested. Hence, change source code so that this does assume this.
- Test all assumptions in `fmpz_CRT`, which should increase code coverage in this function.
- Cleanup test for `fmpz_mat_det` and test for bigger sizes as this is not covered at the moment.

Edit: Mistake for `n_sqrtmodn`.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
> In ulong_extras/sqrtmodn.c, the modulo is allowed to be zero, which is not tested and is not mathematically well-defined. Remove this allowance and state this in the documentation.

The code was not handling modulus 0, but modulus 1 (= 0 prime factors), which is well-defined and should continue to work.

**Comment by albinahlback** [comment]
@fredrik-johansson Could you add `CODECOV_TOKEN` to the secrets? The Codecov upload seems to now fail if this is not added. You may find this section useful: https://github.com/codecov/codecov-action#usage. For reference, see https://github.com/codecov/codecov-action/issues/1138.

**Comment by albinahlback** [comment]
Will merge if there is no more complaints.

**Comment by fredrik-johansson** [comment]
No complaints. Thanks.

**Pull request merged**
