### PR TITLE
Add examples to CI

### PR DESCRIPTION
**Pull request by albinahlback**
Solves #1266

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
This will be very useful. Maybe put the test commands in a script file and have it executed by ``make check`` (or something like ``make check examples`` if we don't want it by default)?

**Comment by albinahlback** [comment]
> This will be very useful. Maybe put the test commands in a script file and have it executed by `make check` (or something like `make check examples` if we don't want it by default)?

Hmm, in my opinion, if we want to have something like `make check MOD=examples`, I think the tests for the examples should be a little bit more thorough. At least it should **run all examples** and **check the outputs**. This is just checking that it doesn't crash when running a subset of all examples.

**Comment by fredrik-johansson** [comment]
Yes, I agree. But one has to start somewhere.

**Comment by albinahlback** [comment]
You can now run `make checkexamples`. I hope this is something of the sort you are looking for. The script `dev/check_examples.sh` requires Perl.

This actually checks a subset of the examples.

**Comment by albinahlback** [comment]
A big note: As this only checks that the output is exactly the same every time, it may be the case that any change in algorithms whatsoever (like more accurate algorithms in Arb, that is, a smaller interval for the ball) will cause the example checks to fail.

**Pull request merged**
