### PR TITLE
Specify modules to specifically unroll loops

### PR DESCRIPTION
**Pull request by albinahlback**
Remove `-funroll-loops` as default flag

Treats #1284

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
We will need to check carefully for regressions before merging this. Here is one:

```
$ build/examples/poly_roots a 200
computing squarefree factorization...
cpu/wall(s): 0 0
200 roots with multiplicity 1
searching for 200 roots, 200 deflated
prec=32: 0 isolated roots | cpu/wall(s): 0.186 0.185
prec=64: 0 isolated roots | cpu/wall(s): 0.483 0.483
prec=128: 200 isolated roots | cpu/wall(s): 0.263 0.264
done!
cpu/wall(s): 0.933 0.933
```

```
$ build/examples/poly_roots a 200
computing squarefree factorization...
cpu/wall(s): 0 0
200 roots with multiplicity 1
searching for 200 roots, 200 deflated
prec=32: 0 isolated roots | cpu/wall(s): 0.206 0.206
prec=64: 0 isolated roots | cpu/wall(s): 0.501 0.5
prec=128: 200 isolated roots | cpu/wall(s): 0.279 0.28
done!
cpu/wall(s): 0.987 0.986
```

**Comment by albinahlback** [comment]
Yeah, we would really need a benchmark suite...

**Comment by fredrik-johansson** [comment]
It is hard to detect any consistent slowdown with this patch. If anything, running the test suite seems to be 1% faster, presumably because of the benefits of reduced code size.

As such, I'd be fine with merging this and re-testing specific benchmarks with full funrolling when doing future performance tuning.

**Comment by fredrik-johansson** [comment]
There is code in ``mpn_extras`` and ``fft_small`` that definitely ought to be unrolled completely, but presumably ``-O3`` currently suffices to trigger unrolling with my gcc. We might want to check that this is the case with clang too, or otherwise enable ``-funroll-loops`` at least for ``mpn_extras`` and ``fft_small`` too.

**Comment by fredrik-johansson** [comment]
``qsieve`` is another module where we might want to keep some funrolled loops.

**Comment by albinahlback** [comment]
U stands for unrolled, R for rolled, C for Clang and G for GCC. Here are the results:
```
================== DETAILS ==============   UC      UG      RC      RG
fmpz is_prime 10000000 x 1                0.996   0.893   0.991   0.910
fmpz is_prime 10000000 x 64               1.382   1.366   1.381   1.402
fmpz is_prime 30000 x 128                 1.379   1.369   1.378   1.338
fmpz is_prime 3000 x 256                  0.857   0.878   0.842   0.865
fmpz is_prime 3000 x 512                  1.628   1.630   1.649   1.607
fmpz is_prime 1500 x 1024                 5.260   5.277   5.282   5.322
fmpz is_probabprime 10000000 x 1          0.991   0.892   0.991   0.908
fmpz is_probabprime 10000000 x 64         1.380   1.360   1.387   1.399
fmpz is_probabprime 1000000 x 128         0.698   0.727   0.700   0.700
fmpz is_probabprime 100000 x 256          0.159   0.159   0.159   0.158
fmpz is_probabprime 10000 x 1024          0.280   0.280   0.278   0.280
fmpz is_probabprime 1000 x 4096           1.038   1.046   1.041   1.095
fmpz factor 1000000 x 1                   0.593   0.658   0.596   0.690
fmpz factor 100000 x 32                   0.839   0.904   0.836   0.981
fmpz factor 10000 x 64                    2.239   2.519   2.239   2.633
fmpz factor 100 x 128                     2.053   1.978   2.051   1.947
fmpz factor 30 x 192                      6.931   6.899   6.846   6.871
fmpz factor 10 x 224                     19.245  18.578  18.609  18.897
fmpz_poly factor P1                       0.014   0.015   0.017   0.014
fmpz_poly factor P2                       0.027   0.027   0.028   0.027
fmpz_poly factor P3                       0.052   0.052   0.052   0.051
fmpz_poly factor P4                       0.438   0.438   0.438   0.437
fmpz_poly factor P5                       0.019   0.032   0.019   0.019
fmpz_poly factor P6                       0.025   0.028   0.025   0.025
fmpz_poly factor P7                       1.053   1.019   1.054   1.039
fmpz_poly factor P8                       0.299   0.293   0.299   0.298
fmpz_poly factor M12_5                    1.071   1.027   1.074   1.047
fmpz_poly factor M12_6                   13.119  13.269  12.992  13.385
fmpz_poly factor T1                       0.263   0.233   0.263   0.238
fmpz_poly factor T2                       0.279   0.253   0.280   0.255
fmpz_poly factor T3                       5.647   5.275   5.572   5.374
fmpz_poly factor H1                       5.208   4.719   5.200   4.895
fmpz_poly factor S7                       0.357   0.333   0.356   0.340
fmpz_poly factor S8                       4.206   3.928   4.188   4.106
fmpz_poly factor C1                       1.378   1.345   1.387   1.378
nmod_mpoly factor bivariate powers       20.349  18.601  20.340  18.586
nmod_mpoly factor p = 43051               2.016   1.787   2.015   1.768
nmod_mpoly factor p = 2                   0.306   0.322   0.308   0.317
nmod_mpoly factor 4 vars, p = 2           0.319   0.328   0.305   0.318
nmod_mpoly factor 4 vars, p = 3           0.257   0.275   0.255   0.266
nmod_mpoly factor 4 vars, p = 11          0.651   0.690   0.649   0.666
nmod_mpoly factor 4 vars, p = 257         2.882   2.939   2.877   2.880
nmod_mpoly factor 4 vars, p = 43051       2.749   2.814   2.752   2.749
fmpz_mpoly factor 4 variables             3.379   3.409   3.331   3.436
fmpz_mpoly factor 5 variables             0.002   0.002   0.002   0.002
arb pi 10000000                           5.038   5.453   4.984   5.450
arb pi 10000000 -threads 8                2.535   2.815   2.548   2.912
arb bernoulli 1000000 -threads 8         16.449  16.773  16.463  16.866
arb partitions 1e12 -threads 8            2.683   2.802   2.689   2.859
arb zeta_zeros 1000 -prec 333 -threads 8  4.519   4.416   4.460   4.376
arb keiper_li 3000 -threads 8             2.397   2.392   2.389   2.413
arb integrals -i 4 -prec 1000             0.321   0.324   0.325   0.320
arb hilbert_mat 120                       1.072   1.056   1.070   1.064
arb hilbert_matrix -eig 50                1.855   1.922   1.843   1.893
arb poly_roots a 256                      6.595   6.583   6.593   6.459
arb class_poly -1000000                   0.413   0.420   0.413   0.418
calcium huge_expr                         5.376   5.477   5.352   5.463
==================== BY GROUP =========================================
fmpz (18 benchmarks)                     47.948  47.413  47.256  48.003
fmpz_poly (17 benchmarks)                33.455  32.286  33.244  32.928
nmod_mpoly (8 benchmarks)                29.529  27.756  29.501  27.550
fmpz_mpoly (2 benchmarks)                 3.381   3.411   3.333   3.438
arb (11 benchmarks)                      43.877  44.956  43.777  45.030
calcium (1 benchmarks)                    5.376   5.477   5.352   5.463
====================== TOTAL ==========================================
all (57 benchmarks)                     163.566 161.299 162.463 162.412
```

**Comment by albinahlback** [comment]
Btw, I use `--disable-debug` and I am on Skylake with Clang 16.0.6 and GCC 13.2.1.

**Comment by albinahlback** [comment]
I think it is safe to say that unrolling is almost never good for Clang.

For GCC however, it seems that it usually favors unrolling most of the time. But the difference is not that great, and I would very much suggest that we do not unroll more complete modules, but rather check what things we can gain time on locally.

**Comment by fredrik-johansson** [comment]
Sure, it looks OK to me. It will be easy to experiment with turning it back on for individual modules anyway.

**Pull request merged**
