### PR TITLE
Generic expression parsing

### PR DESCRIPTION
**Pull request by fredrik-johansson**
* Add generic implementation of ``gr_set_str`` based on the ``mpoly`` expression parsing code. Things like this now work automagically:

```
    >>> QQ("2 / 3")
    2/3
    >>> PolynomialRing_gr_mpoly(NumberField(x**2+1, "a"), 2, ["x", "y"])("(a+x+2*y)^2")
    x^2 + 4*x*y + (2*a)*x + 4*y^2 + (4*a)*y - 1
    >>> qqbar("(-1/2*i)^(1/3)")
    Root a = 0.687365 - 0.396850*I of 4*a^6+1
    >>> CC("(-1/2*i)^(1/3)")
    ([0.687364818499301 +/- 6.67e-16] + [-0.396850262992050 +/- 5.78e-16]*I)
```

* Add ``fmpz_mpoly_q_set_str_pretty`` / ``fmpz_mpoly_q_get_str_pretty`` as requested in #1720. 

* Some generics bugfixes, support for changing generator names in more places, etc.

* This is intended to make the ``mpoly`` parsing code redundant. That will be the case when we have generics wrappers for the other mpolys that currently use parsing (``fmpz_mod_mpoly``, etc.).

* If useful, we could add wrappers for other types too (``fmpz_poly_set_str_pretty``, ... ).

* The code was originally intended for parsing multivariate polynomials, so it has some limitations for more general kinds of objects.

* For example: for parsing dense univariate polynomials, the complexity is quadratic in the degree (because monomials have full length representation). This can be avoided by parsing to a sparse type, then converting back to the dense type.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Improvements that could go in a followup issue:

* Support function calls (e.g. ``sqrt``)
* Support floating-point literals
* Lazy terminal nodes and custom literals (for ``fexpr``; Arb ball literals etc.)
* Better handling of exponents
* Faster polynomial parsing
* Postfix ``!`` would be cute
* Better error reporting
* Parsing vectors and matrices

**Comment by albinahlback** [comment]
Would it be easy to increase the code coverage of `_gr_parse_add_terminal` and `_gr_parse_push_expr`?

**Comment by albinahlback** [comment]
Although I do not understand the whole code, it looks really good!

**Comment by fredrik-johansson** [comment]
> Would it be easy to increase the code coverage of _gr_parse_add_terminal and _gr_parse_push_expr?

I think so. We just need to add some test cases with more difficult expressions.

**Pull request merged**
