### PR TITLE
Alter coverage reports

### PR DESCRIPTION
**Pull request by albinahlback**
- Create test for `fmpq_equal_[si/ui]`
- Exclude `generic_files/exception.c` in codecov (as we do not expect to use any exceptions in the tests). However, it would be nice to test that these works as intended.
- Convert throws through `flint_abort` to `flint_throw`. Most cases had something of the sort
  ```c
  flint_printf("some message\n");
  flint_abort();
  ```
  which was converted to `flint_throw(FLINT_ERROR, "some message\n")`, but some cases simply used `flint_abort()` without any message. For these cases I replaced them with `flint_throw(FLINT_ERROR, "(%s)\n", __func__)`. Two (?) cases was omitted from this PR as they utilized some print function, such as `mag_printd`.
- Alter `make coverage`. Now this will **not** produce any HTML pages, as `make coverage_html` now will. Both of these are now multithreaded. `make coverage` will now exclude lines containing `flint_throw`, but also the regexp `^}$` as `lcov` seems to mark the end of some void functions with no hits.

In the end, I would like to replace every `flint_throw` by a macro `FLINT_THROW(SOME_ERROR_CODE)` which evaluates to `flint_throw(SOME_ERROR_CODE, __func__)` which will print what the error is in what function. This will take up little space in the binary and with a range of error codes we can be very specific. I haven't thought about printing other inputs, but perhaps we can manage that in some nice way.

I hope that `lcov` now works in conjunction with codecov.

### CODE REVIEW

**Comment by albinahlback** [comment]
Looking good, @fredrik-johansson?

`lcov` seems to take about 4 minutes to complete, which is about 4 minutes more than `gcov`. Moreover, installing all Perl packages takes about 2 minutes.

I don't like that we have to install `lcov` from source in order to get `--omit-lines`, but it is what it is.

**Comment by fredrik-johansson** [comment]
Yeah this doesn't even work for me:

```
$ make coverage
lcov -j  --capture --omit-lines "flint_throw" --omit-lines '^}$' --exclude "*test/t-*.c" --exclude "*test/main.c" --exclude "/usr/*" --directory build --output-file build/coverage/coverage.info
lcov: Unknown option: j
lcov: Unknown option: omit-lines
lcov: Unknown option: omit-lines
Use lcov --help to get usage information

$ lcov --version
lcov: LCOV version 1.14
```

**Comment by albinahlback** [comment]
> Yeah this doesn't even work for me:
> 
> ```
> $ make coverage
> lcov -j  --capture --omit-lines "flint_throw" --omit-lines '^}$' --exclude "*test/t-*.c" --exclude "*test/main.c" --exclude "/usr/*" --directory build --output-file build/coverage/coverage.info
> lcov: Unknown option: j
> lcov: Unknown option: omit-lines
> lcov: Unknown option: omit-lines
> Use lcov --help to get usage information
> 
> $ lcov --version
> lcov: LCOV version 1.14
> ```

Sorry, see my edited reply. Do you want me to hardcode the coverage instead in `.github/workflows/CI.yml`, and revert the `Makefile` changes?

**Comment by fredrik-johansson** [comment]
> Sorry, see my edited reply. Do you want me to hardcode the coverage instead in .github/workflows/CI.yml, and revert the Makefile changes?

Sure.

**Comment by albinahlback** [comment]
Will merge these tests passes.

**Pull request merged**
