### PR TITLE
Low-level fixes

### PR DESCRIPTION
**Pull request by albinahlback**

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
> [Use mulx instruction in umul_ppmm if possible](https://github.com/flintlib/flint/pull/1782/commits/5641c60ab1522a50976cd83e71deb34821c653c9)

This *should* be better, but IIRC I timed some functions with such a version and saw a slowdown, maybe for completely random reasons, so it would be worth checking various benchmarks.

**Comment by fredrik-johansson** [comment]
> [Remove volatile keyword from inline assembly division](https://github.com/flintlib/flint/pull/1782/commits/b350f0efb86554ccab5efb343d17a80f38d0269e)

The ``volatile`` is there to prevent wrong code generation: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82677

**Comment by albinahlback** [comment]
> > [Remove volatile keyword from inline assembly division](https://github.com/flintlib/flint/pull/1782/commits/b350f0efb86554ccab5efb343d17a80f38d0269e)
> 
> The `volatile` is there to prevent wrong code generation: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82677
> 
> Edit: I couldn't find the original issue for this; but in fact it was first found in Arb: [fredrik-johansson/arb#194](https://github.com/fredrik-johansson/arb/issues/194)
> 
> Here is the bugfix commit in flint: [b41022e](https://github.com/flintlib/flint/commit/b41022e7007282147ad9e6cad245b7df6ffa9f09)

Thanks, good catch! I will drop this commit.

**Comment by albinahlback** [comment]
> > [Use mulx instruction in umul_ppmm if possible](https://github.com/flintlib/flint/pull/1782/commits/5641c60ab1522a50976cd83e71deb34821c653c9)
> 
> This _should_ be better, but IIRC I timed some functions with such a version and saw a slowdown, maybe for completely random reasons, so it would be worth checking various benchmarks.

Perhaps GCC can optimize code around `mul`, but is unaware of how to optimize around `mulx`.

**Comment by albinahlback** [comment]
Benchmark shows that `mulx` is faster (Skylake with GCC 13.2.1):
```
                                            mul    mulx
==================== DETAILS ==========================
fmpz is_prime 10000000 x 1                0.894   0.898
fmpz is_prime 10000000 x 64               1.371   1.365
fmpz is_prime 30000 x 128                 1.360   1.357
fmpz is_prime 3000 x 256                  0.815   0.857
fmpz is_prime 3000 x 512                  1.598   1.627
fmpz is_prime 1500 x 1024                 5.100   5.098
fmpz is_probabprime 10000000 x 1          0.897   0.898
fmpz is_probabprime 10000000 x 64         1.360   1.362
fmpz is_probabprime 1000000 x 128         0.709   0.709
fmpz is_probabprime 100000 x 256          0.159   0.158
fmpz is_probabprime 10000 x 1024          0.300   0.279
fmpz is_probabprime 1000 x 4096           1.041   1.041
fmpz factor 1000000 x 1                   0.630   0.691
fmpz factor 100000 x 32                   0.875   0.983
fmpz factor 10000 x 64                    2.518   2.544
fmpz factor 100 x 128                     2.011   1.938
fmpz factor 30 x 192                      7.028   6.983
fmpz factor 10 x 224                     19.508  19.416
fmpz_poly factor P1                       0.020   0.015
fmpz_poly factor P2                       0.026   0.026
fmpz_poly factor P3                       0.050   0.050
fmpz_poly factor P4                       0.369   0.370
fmpz_poly factor P5                       0.018   0.018
fmpz_poly factor P6                       0.025   0.025
fmpz_poly factor P7                       0.957   0.951
fmpz_poly factor P8                       0.283   0.283
fmpz_poly factor M12_5                    0.944   0.964
fmpz_poly factor M12_6                   12.826  12.807
fmpz_poly factor T1                       0.231   0.230
fmpz_poly factor T2                       0.250   0.248
fmpz_poly factor T3                       4.520   4.498
fmpz_poly factor H1                       4.624   4.605
fmpz_poly factor S7                       0.312   0.312
fmpz_poly factor S8                       3.617   3.593
fmpz_poly factor C1                       1.334   1.323
nmod_mpoly factor bivariate powers       17.748  17.628
nmod_mpoly factor p = 43051               1.377   1.372
nmod_mpoly factor p = 2                   0.320   0.322
nmod_mpoly factor 4 vars, p = 2           0.328   0.325
nmod_mpoly factor 4 vars, p = 3           0.271   0.272
nmod_mpoly factor 4 vars, p = 11          0.677   0.684
nmod_mpoly factor 4 vars, p = 257         2.904   2.894
nmod_mpoly factor 4 vars, p = 43051       2.787   2.778
fmpz_mpoly factor 4 variables             3.352   3.349
fmpz_mpoly factor 5 variables             0.002   0.002
arb pi 10000000                           5.464   5.462
arb pi 10000000 -threads 8                2.992   2.951
arb bernoulli 1000000 -threads 8         17.086  17.020
arb partitions 1e12 -threads 8            2.860   2.861
arb zeta_zeros 1000 -prec 333 -threads 8  4.367   4.395
arb keiper_li 3000 -threads 8             2.452   2.460
arb integrals -i 4 -prec 1000             0.325   0.328
arb hilbert_mat 120                       1.030   1.034
arb hilbert_matrix -eig 50                1.874   1.850
arb poly_roots a 256                      6.499   6.499
arb class_poly -1000000                   0.422   0.421
calcium huge_expr                         5.030   5.043
==================== BY GROUP ==========================
fmpz (18 benchmarks)                     48.174  48.204
fmpz_poly (17 benchmarks)                30.406  30.318
nmod_mpoly (8 benchmarks)                26.412  26.275
fmpz_mpoly (2 benchmarks)                 3.354   3.351
arb (11 benchmarks)                      45.371  45.281
calcium (1 benchmarks)                    5.030   5.043
====================== TOTAL ===========================
all (57 benchmarks)                     158.747 158.472
```

**Comment by albinahlback** [comment]
Will merge if it passes.

**Comment by fredrik-johansson** [comment]
> ```all (57 benchmarks)                     158.747 158.472```

Surely within measurement error (in other words, no big regression).

**Comment by albinahlback** [comment]
Implemented squaring up to n = 10 and improved previous squaring. Not super fast for n > 7, but it is something. As you are running out of registers, you have to resort to memory, and there it seems to be a cutoff at n = 8 or 9 for when AVX starts to become faster when multiplying by two.

**Comment by fredrik-johansson** [comment]
On my computer the new n = 9 and n = 10 basecases look slower than the C code I had:

```
mpn_sqr_basecase / flint_mpn_sqr
m =  1:   1.00x
m =  2:   1.10x
m =  3:   1.28x
m =  4:   1.57x
m =  5:   1.50x
m =  6:   1.52x
m =  7:   1.37x
m =  8:   1.09x
m =  9:   1.07x
m = 10:   0.95x
```

**Pull request merged**
