### PR TITLE
Add flint_mpn_mulhigh for n <= 8

### PR DESCRIPTION
**Pull request by albinahlback**
and a test and (probably) a bad docstring.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Some C code to compare with:

https://gist.github.com/fredrik-johansson/2f88376c5dd9dc0b668e7b6d91b9d266

**Comment by fredrik-johansson** [comment]
We need to decide whether the output should be written to *{rp, n + 1}* or *{rp + n - 1, n + 1}*.

This doesn't matter for assembly versions, but the recursive mulhigh algorithm (used beyond the basecase) requires having the option to use lower limbs as scratch space, or even writing the full product when the operands are FFT-sized.

**Comment by albinahlback** [comment]
I think I changed my mind. For the assembly code, I will push the upper $n$ limbs to `rp`, but return the $(n - 1)$-least significant limb. With this, one does not need to have space for $n + 1$ limbs (I'm thinking of multiplication in Arb), to the needing to shift it down or whatever.

**Comment by albinahlback** [comment]
I suppose one would also like to normalize the limbs (mainly thinking of Arb). It is way more efficient to do it via an `adc`-chain while they are in the registers than to later read memory into YMM registers, shift, and then write back to memory. If this is desirable, let me know. One could then set the `rdx` register to signify whether a shift was made or not.

**Comment by albinahlback** [comment]
Some profiling data:
```
           GMP       MPFR
n =  1:   1.59x     3.20x
n =  2:   1.71x     4.10x
n =  3:   2.58x     3.52x
n =  4:   2.34x     3.13x
n =  5:   2.23x     2.81x
n =  6:   2.26x     2.71x
n =  7:   2.29x     2.44x
n =  8:   2.35x     2.35x
n =  9:   2.29x     2.09x
n = 10:   2.32x     2.01x
n = 11:   2.36x     1.94x
n = 12:   2.13x     1.71x
```
Will merge when tests pass.

**Comment by fredrik-johansson** [comment]
Very impressive! I agree that the interface returning the low limb makes sense. Now we will have to think about how to implement it for larger n.

**Pull request merged**
